"""Hand-written descriptions used by refgen.py where the source has none.

PROC_DOC[name]       one-sentence purpose of a procedure
ARG_DOC[name]        generic meaning of a dummy argument / derived-type component
ARG_PROC[(proc,arg)] override for a given procedure
"""

PROC_DOC = {
    # ---------------------------------------------------------- ANALYSES
    'RUN_STATIC_ANALYSIS': 'Analysis 101: assemble K, build loads and constraints, eliminate constraints exactly, factorize with PARDISO and solve K u = F.',
    'RUN_MODAL_ANALYSIS': 'Analysis 103: assemble K and M, reduce to the free DOF, solve K x = lambda M x with shift-invert ARPACK (or dense LAPACK) and sort the modes.',
    'RUN_MUL2': 'Program driver: create the output directories, read the model, build the cache, run 101 or 103, write all outputs and the warning report.',
    'REMEMBER_WARNING': 'Store the warning of a step so that it is written to REPORT/WARNING_file.dat.',
    'ASSEMBLE_MODEL_SYSTEM': 'Assemble global K (and M) in CSR: DOF lists, pattern, parallel element evaluation in chunks, serial deterministic scatter.',
    'MARK_LAGRANGE_DOFS': 'Tag the local DOFs of an element that belong to a Lagrange expansion (table id and term) for the structural-zero pattern.',
    'BUILD_COUPLING_TABLES': 'For every expansion mesh build COUPLED(t,s): do expansion nodes t and s share a sub-element?',
    'EVALUATE_ELEMENT': 'K (and M) of one element; thread-safe because it only reads shared data.',
    'CHECK_MECHANICAL_MODEL': 'Reject models using fields other than U, V, W (not supported by 101/103) or without elements.',
    'BUILD_MODEL_CACHE': 'Preprocessing pipeline: DOF layout, element frames, Gauss rules and layout, structural/expansion/combined geometry and material cache.',
    'BUILD_EXPANSION_POINT_ORDERS': 'Gauss points per direction required by each expansion mesh (Taylor order N needs N+1).',
    'PREPARE_ELEMENT_MITC': 'Tying data of one element when MITC is requested for its dimension; warning and full integration if the topology has no table.',
    # ---------------------------------------------------------- ASSEMBLY
    'BUILD_DOF_LAYOUT': 'Compute the number of terms of every (node, field) and the field-major global numbering.',
    'NODE_FIELD_TERM_COUNT': 'Terms of one field at one node from its expansion family and the expansion meshes of the incident elements.',
    'LAGRANGE_TERM_COUNT': 'Number of nodes of an expansion mesh (terms of a Lagrange expansion).',
    'EXPANSION_DIMENSION_FOR_ELEMENT': 'Natural dimension of the sub-elements of an expansion mesh (-1 unknown, -2 mixed).',
    'GLOBAL_DOF': 'Global DOF number of (node index, field, term).',
    'CLEAR_LAYOUT': 'Release the arrays of a DOF layout.',
    'BUILD_AND_ASSEMBLE_SPARSE_SYSTEM': 'Pattern + assembly from dense element matrices (reference path used by the unit tests).',
    'BUILD_SPARSE_PATTERN': 'CSR pattern from the DOF lists of dense element matrices.',
    'BUILD_PATTERN_FROM_DOF_LISTS': 'Two-pass CSR pattern from the DOF lists alone, skipping pairs of Lagrange terms that cannot couple.',
    'ARE_COUPLED': 'False only for two Lagrange DOFs of the same table whose terms do not share a sub-element.',
    'SORT_SEGMENT': 'Sort the column indices of one CSR row (insertion for short rows, heap sort for long ones).',
    'SIFT_COLUMN': 'Heap-sort helper for SORT_SEGMENT.',
    'SCATTER_ELEMENT': 'Add an element K/M pair into the CSR arrays (binary search per entry; structural zeros skipped).',
    'BUILD_SCATTER_MAPS': 'Precompute CSR_POSITION of every element entry.',
    'ASSEMBLE_ELEMENT_MATRICES': 'Add dense element matrices through precomputed scatter maps.',
    'FIND_CSR_POSITION': 'Position of (row, column) in the CSR arrays, 0 when absent.',
    'SORT_COORDINATES': 'Sort (row, column) pairs lexicographically.',
    'SIFT_DOWN': 'Heap-sort helper.',
    'PAIR_LESS': 'Lexicographic comparison of two (row, column) pairs.',
    'SWAP_PAIR': 'Swap two (row, column) pairs.',
    'CLEAR_SPARSE_SYSTEM': 'Release a CSR system.',
    'SPARSE_MULTIPLY': 'y = A x for a full CSR matrix (row-parallel with OpenMP, result independent of the thread count).',
    'BUILD_REDUCED_PATTERN': 'CSR pattern of the sub-matrix on the unconstrained DOFs, with the source position of every entry.',
    'REDUCE_VALUES': 'Copy the values of a full matrix into the reduced pattern.',
    'EXPAND_VECTOR': 'Scatter a reduced vector back to the full DOF numbering (constrained DOFs = 0).',
    # ---------------------------------------------------------- BASE
    'IS_WINDOWS': 'True when the program runs on Windows (selects shell syntax).',
    'ENSURE_DIRECTORY': 'Create a relative directory if it does not exist.',
    'LOG_INITIALIZE': 'Select normal or debug logging.',
    'LOG_INFO': 'Print an informational line on the console.',
    'LOG_WARNING': 'Print a warning line.',
    'LOG_ERROR': 'Print an error line on the error unit.',
    'LOG_DEBUG': 'Print a line only in debug mode.',
    'IS_DEBUG_MODE': 'Return the debug flag.',
    'INITIALIZE_RUNTIME': 'Start the global timer and print the banner.',
    'FINALIZE_RUNTIME': 'Print the CPU and wall time of the run.',
    'SORT_PERMUTATION': 'Permutation that sorts a key array in ascending order (heap sort).',
    'BINARY_SEARCH': 'Position of a key in a permutation-sorted array, 0 if absent.',
    'HAS_DUPLICATE_KEYS': 'True when a key array contains a repeated value.',
    'CLEAR_STATUS': 'Reset a status to OK.',
    'SET_WARNING': 'Record a warning (an existing error is not overwritten).',
    'SET_ERROR': 'Record an error with its source and message.',
    'STATUS_IS_OK': 'True when the status is not an error (warnings are allowed).',
    'MERGE_STATUS': 'Fold a step status into a phase status: first error wins, warnings are counted.',
    'UPPERCASE': 'Convert a string to upper case in place.',
    'TIMER_START': 'Start a named timer (CPU and wall clock).',
    'TIMER_STOP': 'Stop a timer.',
    'TIMER_CPU_SECONDS': 'Elapsed CPU seconds.',
    'TIMER_WALL_SECONDS': 'Elapsed wall-clock seconds.',
    # ---------------------------------------------------------- BOUNDARY
    'BUILD_MECHANICAL_BOUNDARY_DATA': 'Resolve D-PLANE and F-POINT records into a constrained-DOF set with prescribed values and a global force vector.',
    'ADD_PLANE_CONSTRAINT': 'Constrain the DOFs of every node/term whose physical position lies on the plane A x + B y + C z + D = 0.',
    'ADD_POINT_FORCE': 'Add a point load at a physical position: nodal term for Lagrange, projection on all monomials for Taylor.',
    'APPLY_STATIC_CONSTRAINTS': 'Exact symmetric elimination: F = F - K u_c, zero rows/columns of constrained DOFs, unit diagonal.',
    'SET_DOF_CONSTRAINT': 'Mark one DOF as constrained; conflicting values are an error.',
    'FIRST_ELEMENT': 'First element incident to a node (0 if none).',
    'EXPANDED_POINT': 'Physical position of a section point: node + frame * local section coordinate.',
    'POINT_ON_PLANE': 'Plane test with a scaled tolerance.',
    'FIND_EXPANSION_AXES': 'Active local axes and dimension of an expansion mesh from its node extent.',
    'CLEAR_BOUNDARY_DATA': 'Release the constraint set and force vector.',
    # ---------------------------------------------------------- CUF
    'TAYLOR_BASIS_TERM_COUNT': 'Number of Taylor monomials of order N in 1D (N+1) or 2D ((N+1)(N+2)/2).',
    'EVALUATE_TAYLOR_BASIS': 'All Taylor monomials and their gradients at a section point.',
    'EVALUATE_TAYLOR_TERM': 'One Taylor monomial x^a z^b and its gradient.',
    'INTEGER_POWER': 'x**n by repeated multiplication (no overflow of the generic power).',
    'STIFFNESS_NUCLEUS': 'Scalar fundamental nucleus: weight * B_i^T C B_j.',
    'STIFFNESS_BLOCK_NUCLEUS': '3x3 stiffness nucleus of a pair of nodes/terms.',
    'MASS_NUCLEUS': 'Scalar mass nucleus: rho N_i N_j weight for equal components.',
    'MASS_BLOCK_NUCLEUS': '3x3 mass nucleus (diagonal).',
    'ROTATE_BLOCK_TO_GLOBAL': 'Rotate a 3x3 block from the local to the global frame.',
    'EVALUATE_POINT_FACTORS': 'N, grad N (structural node) and F, grad F (expansion term) at a cached Gauss point.',
    'EVALUATE_POINT_BASIS': 'Value and gradient of the combined basis N F at a cached Gauss point.',
    'EVALUATE_FIELD_BASIS': 'One scalar basis term of one field at one point (composition of N and F).',
    'EVALUATE_EXPANSION_FACTOR': 'Expansion factor F_tau and its local gradient (Taylor monomial or Lagrange node function).',
    # ---------------------------------------------------------- ELEMENTS
    'ACCUMULATE_UPPER_PRODUCT': 'Add A^T B to the upper triangle of a matrix, 4-column register blocking, optional column selection.',
    'ACCUMULATE_PRODUCT': 'Add A^T B to a full matrix (same blocking).',
    'COLUMN': 'Column of the matrix addressed by a (possibly selected) index.',
    'ADD_ENTRY': 'Add a value to one matrix entry.',
    'BUILD_LINEAR_ELEMENT_MATRICES': 'K and M of one element: separable kernel when applicable, otherwise batched point-by-point reference kernel.',
    'TRY_SEPARABLE': 'Call the separable kernel (internal helper).',
    'ADD_MASS': 'Add the mass contribution of a batch of points, one product per displacement component.',
    'MIRROR_UPPER_TRIANGLE': 'Copy the upper triangle of K (and M) into the lower one.',
    'EVALUATE_LOCAL_DOF': 'Basis value and strain column B(:,dof) of one local DOF at one Gauss point, with MITC tying.',
    'BUILD_ELEMENT_DOF_LIST': 'Local DOF list of an element: global numbers, structural node, field and term of every local DOF.',
    'VALIDATE_INPUT': 'Consistency checks of the databases before the element kernel runs.',
    'CLEAR_ELEMENT_MATRIX': 'Release an element-matrix container.',
    'MITC_IS_AVAILABLE': 'True for topologies with a tying table (B2 B3 B4 Q4 Q9 H8 H20 H27).',
    'MITC_PREPARE_ELEMENT': 'Tying table of an element and the shapes/gradients at its tying points.',
    'MITC_CLEAR': 'Reset MITC data (including the tying sets).',
    'DEFINE_TYING': 'Table of tied rows and tying points of a topology.',
    'SET_LIST': 'Set the tying coordinates of one direction.',
    'POINT_OF_SET': 'Natural coordinates of tying point L (first direction fastest).',
    'INTERPOLATION_WEIGHT': 'Tensor Lagrange weights of the tying points at a natural point.',
    'MITC_TIE_COLUMN': 'Replace the tied rows of the strain column of one DOF by their interpolation from the tying points.',
    'BUILD_SEPARABLE_MATRICES': 'Separable CUF kernel: structural and expansion integrals computed separately and combined (Lambda x Em).',
    'PRODUCT_OF': 'Product of the three counts of a tying set.',
    'SAME_SPEC': 'True when two kinematic specifications are identical (family, order, field reference).',
    'PREPARE_PRODUCT': 'Expansion products EM(t,s,k,e) for one pair of specifications.',
    # ---------------------------------------------------------- FEM / GEOMETRY / GAUSS
    'EVALUATE_SHAPE': 'Shape functions and natural derivatives of a topology at a natural point.',
    'SHAPE_B': 'Lagrange line shapes (B2, B3, B4).',
    'SHAPE_Q4': 'Bilinear quadrilateral.', 'SHAPE_Q9': 'Biquadratic quadrilateral.',
    'SHAPE_Q16': 'Bicubic quadrilateral.', 'SHAPE_T3': 'Linear triangle.',
    'SHAPE_T6': 'Quadratic triangle.', 'SHAPE_H8': 'Trilinear hexahedron.',
    'SHAPE_H27': 'Triquadratic hexahedron.',
    'TENSOR_2D': 'Tensor product of 1D Lagrange functions on a quadrilateral.',
    'TENSOR_3D': 'Tensor product of 1D Lagrange functions on a hexahedron.',
    'LAGRANGE_1D': '1D Lagrange polynomial and derivative of given order and node index.',
    'BUILD_STRUCTURAL_GEOMETRY_CACHE': 'Jacobian, determinant, inverse and local-frame shape gradients of every structural Gauss point.',
    'BUILD_EXPANSION_GEOMETRY_CACHE': 'Same for every expansion sub-element and point (the same cache serves all structural points).',
    'BUILD_COMBINED_GAUSS_GEOMETRY': 'Global coordinate and integration weight of every combined (structural x expansion) point.',
    'STRUCTURAL_ACTIVE_AXES': 'Local axes carried by the structural element: y for beams, x-y for plates, x-y-z for solids.',
    'FIND_EXPANSION_ACTIVE_AXES': 'Local axes spanned by the expansion mesh (the largest node extents).',
    'GET_EXPANSION_NODE_COORDINATE': 'Coordinate of an expansion node by id.',
    'ALLOCATE_STRUCTURAL_CACHE': 'Allocate the structural geometry cache.',
    'ALLOCATE_EXPANSION_CACHE': 'Allocate the expansion geometry cache.',
    'CLEAR_STRUCTURAL_CACHE': 'Release the structural cache.', 'CLEAR_EXPANSION_CACHE': 'Release the expansion cache.',
    'CLEAR_COMBINED_GEOMETRY': 'Release the combined geometry.',
    'BUILD_GAUSS_MATERIAL_CACHE': 'Resolve every lamination into a rotated stiffness matrix and map each Gauss point to its entry.',
    'CLEAR_MATERIAL_CACHE': 'Release the material cache.',
    'BUILD_REFERENCE_RULE_DATABASE': 'One reference rule (points, weights, shapes, derivatives) per (topology, points-per-direction).',
    'BUILD_REFERENCE_RULE': 'Evaluate shapes and derivatives at the points of one rule.',
    'BUILD_GAUSS_LAYOUT': 'Global Gauss-point numbering: element, sub-element, structural point, expansion point.',
    'ADD_TOPOLOGY': 'Register a (topology, order) pair once.',
    'FIND_REFERENCE_RULE': 'Index of the rule of a topology and order, 0 if missing.',
    'EXPANSION_POINTS': 'Points per direction required by a mesh (0 = default rule).',
    'EXPANSION_MESH_ORDER': 'Points per direction of an expansion mesh given the per-mesh need.',
    'ALLOCATE_LAYOUT': 'Allocate the Gauss layout arrays.', 'CLEAR_LAYOUT_GAUSS': 'Release the Gauss layout.',
    'BUILD_ELEMENT_FRAMES': 'Right-handed local frame of every element from node coordinates and the versor.',
    'BUILD_BEAM_FRAME': 'Beam frame: y along the axis, z from the versor orthogonalised, x = y x z.',
    'BUILD_SURFACE_FRAME': 'Plate frame: z normal to the surface, x from the projected versor, y = z x x.',
    'NORMALIZE': 'Normalise a vector, error if its length is (almost) zero.',
    'CROSS_PRODUCT': 'Vector product.', 'FIND_VECTOR_INDEX': 'Index of a versor by id.',
    'SET_IDENTITY': 'Identity 3x3 matrix.', 'CLEAR_FRAMES': 'Release the frame arrays.',
    'EVALUATE_SQUARE_JACOBIAN': 'Jacobian, determinant, inverse and physical derivatives for a square mapping of dimension 1, 2 or 3.',
    'INVERT_SMALL_MATRIX': 'Invert a 1x1, 2x2 or 3x3 matrix.',
    'LOCAL_SHAPE_GRADIENT': 'Shape gradients in the local frame from natural derivatives and node coordinates.',
    'EVALUATE_SHAPE_AND_GRADIENT': 'Shapes and local gradients of a structural element at a natural point (used for MITC tying points).',
    'BUILD_DEFAULT_QUADRATURE': 'Default Gauss rule of a topology.',
    'DEFAULT_POINTS_PER_DIRECTION': 'Points per direction of the default rule of line and quadrilateral topologies (0 otherwise).',
    'BUILD_ORDERED_QUADRATURE': 'Tensor rule with a prescribed number of points per direction.',
    'BUILD_LINE_RULE': 'Gauss-Legendre rule on [-1,1].', 'BUILD_TENSOR_RULE': 'Tensor product rule on [-1,1]^d.',
    'BUILD_TRIANGLE_RULE': 'Triangle rule (1 or 3 points).',
    'GAUSS_LEGENDRE_1D': 'Gauss-Legendre points and weights (closed form up to 4, Newton on the Legendre polynomial above).',
    'CLEAR_RULE': 'Release a quadrature rule.',
    # ---------------------------------------------------------- IO
    'NEXT_DATA_LINE': 'Next non-blank, non-comment line of a text file.',
    'READ_ANALYSIS_FILE': 'Read ANALYSIS.dat: solution id, number of modes, shear corrections of beams, plates and solids.',
    'READ_POSTPROCESSING_FILE': 'Read POSTPROCESSING.dat: PARA/GMSH field requests, PNT points and matrix dump flags.',
    'READ_BOUNDARY_CONDITIONS_FILE': 'Read BC.dat (D-PLANE and F-POINT).', 'PARSE_COMPONENTS': 'Parse three displacement tokens; N means free.',
    'READ_CONNECTIVITY_FILE': 'Read CONNECTIVITY.dat: topology, node ids, versor and expansion mesh of every element.',
    'READ_EXPANSION_FILES': 'Read one EXP_MESH / EXP_CONN pair.', 'READ_EXPANSION_SET': 'Read all expansion meshes EXP_*_01 ... NN.',
    'READ_EXPANSION_NODES': 'Read EXP_MESH_nn.dat.', 'READ_EXPANSION_ELEMENTS': 'Read EXP_CONN_nn.dat.',
    'DUPLICATE_NODE_ID': 'True when an id appears twice.', 'DUPLICATE_ELEMENT_ID': 'True when an id appears twice.',
    'READ_KINEMATICS_FILE': 'Read KINEMATICS.dat (field-dependent expansions).', 'DUPLICATE_ID': 'True when an id appears twice.',
    'READ_LAMINATIONS_FILE': 'Read LAMINATION.dat (LAM2 records).',
    'READ_LEGACY_NODES_FILE': 'Read the historical NODES.dat (TE/LE token) and create the kinematics.',
    'REGISTER_KINEMATIC': 'Id of the (family, order) kinematic, created if new.',
    'READ_MATERIALS_FILE': 'Read MATERIAL.dat (ISO-M, ORT-M, MAT-C; other records are accepted and ignored).',
    'STORE_MATERIAL': 'Validate and store one material record.',
    'READ_MODEL': 'Read an input directory into one MODEL_TYPE.', 'FILE_OF': 'Full path of a file of the input directory.',
    'READ_NODES_FILE': 'Read the NODES.dat that carries a kinematic id.',
    'READ_REFERENCE_VECTORS_FILE': 'Read VERSORS.dat.',
    # ---------------------------------------------------------- KINEMATICS / MATERIALS / MODEL
    'COMPOSE_PRODUCT_BASIS': 'Value and gradient of N F: N grad F + F grad N.',
    'BUILD_DISPLACEMENT_COLUMN': 'Strain column of one displacement component for a given scalar gradient.',
    'BUILD_DISPLACEMENT_OPERATOR': '6x3 strain operator B(grad) of a scalar basis function.',
    'RESOLVE_LAMINATION': 'Rotated stiffness (element frame), density and rotation of a lamination.',
    'BUILD_MATERIAL_ROTATION': 'Rotation matrix material <- element frame from the angles about y and z (degrees).',
    'BUILD_ENGINEERING_STRAIN_TRANSFORM': '6x6 transformation of engineering strains under a 3x3 rotation.',
    'ROTATE_STIFFNESS': 'Stiffness in the reference frame: T^T C T.',
    'BUILD_ISOTROPIC_MATERIAL': 'Isotropic stiffness from E, nu, rho (checks nu in (-1, 0.5)).',
    'BUILD_ORTHOTROPIC_MATERIAL': 'Orthotropic stiffness from the nine engineering constants in the (T,L,Z) axes.',
    'BUILD_ANISOTROPIC_MATERIAL': 'Store a user-supplied 6x6 stiffness.', 'FIND_MATERIAL_INDEX': 'Index of a material by id.',
    'INVERT_SYMMETRIC_3X3': 'Invert a symmetric 3x3 matrix.',
    'HAS_EXPANSION_NODE_ID': 'True when the mesh has a node with this id.', 'FIND_EXPANSION_INDEX': 'Index of an expansion mesh by id.',
    'BUILD_NODE_INCIDENCE': 'Node -> incident elements table (CSR).',
    'HAS_KINEMATIC_ID': 'True when the kinematic id exists.', 'FIND_KINEMATIC_INDEX': 'Index of a kinematic by id.',
    'PARSE_EXPANSION_TOKEN': 'Parse TE<n>, LE, HLE<n>, M<n> or NONE into an expansion specification.',
    'READ_SUFFIX': 'Read the integer suffix of a token.', 'INVALID_TOKEN': 'Set the error of an unknown expansion token.',
    'FIND_LAMINATION_INDEX': 'Index of a lamination by id.',
    'HAS_NODE_ID': 'True when a node with this id exists.', 'FIND_NODE_INDEX': 'Index of a node by id (binary search).',
    'BUILD_NODE_INDEX': 'Sorted-id lookup table of the nodes; duplicate ids are an error.',
    'TOPOLOGY_FROM_NAME': 'Topology code from the name in the input (B2, Q9, H27, ...).',
    'TOPOLOGY_NODE_COUNT': 'Number of nodes of a topology.', 'TOPOLOGY_NATURAL_DIMENSION': 'Natural dimension 0..3 of a topology.',
    # ---------------------------------------------------------- POST
    'BUILD_POST_GRID': 'Output grid: every element and sub-element divided into cells with 8, 20 or 27 nodes.',
    'ELEMENT_SPLITS': 'Subdivisions of the cells of an element according to its dimension.',
    'CELL_LIMITS': 'Natural coordinates of the nodes of cell i of n along one direction.',
    'SPLIT_NATURAL': 'Split a 3-component natural point into structural and expansion natural coordinates.',
    'COLLAPSE_TRIANGLE': 'Map a square point to a triangle point (collapsed map).',
    'VTK_CELL_ORDER': 'Node order of a cell in VTK output.', 'GMSH_CELL_ORDER': 'Node order of a cell in GMSH output.',
    'CLEAR_POST_GRID': 'Release a post grid.',
    'PREPARE_OUTPUT_DIRECTORIES': 'Create STATIC, DYNAMIC, WORK and REPORT.',
    'WRITE_STATIC_OUTPUT': 'All 101 outputs: points, fields, matrix dumps.',
    'EVALUATE_GRID_STATES': 'Displacement, strain and stress at every grid node (cells in parallel).',
    'EVALUATE_CELL_STATES': 'Same for one cell.',
    'WRITE_POST_POINTS': 'POST_POINT.dat: locate each requested point and write its row (NaN row + warning if outside).',
    'WRITE_POINT_HEADER': 'Header line of POST_POINT.dat.', 'WRITE_POINT_ROW': 'One result row (46 columns).',
    'WRITE_MISSING_POINT_ROW': 'Row of NaN for a point outside the model.',
    'FIND_MESH': 'Expansion mesh index of an element.',
    'WRITE_VTK_GEOMETRY': 'Write points and cells of a VTK file.', 'WRITE_VTK_VECTOR': 'Write a VTK vector field.',
    'WRITE_VTK_SCALAR': 'Write a VTK scalar field.', 'SELECT_FRAME': 'Choose local or global components for output.',
    'VON_MISES': 'Von Mises equivalent stress.', 'WRITE_STATIC_VTK': 'RESULTS_PARA_nn.vtk.',
    'WRITE_GMSH_GEOMETRY': 'Write nodes and elements of a GMSH file.', 'WRITE_GMSH_DATA': 'Write one GMSH view.',
    'WRITE_STATIC_GMSH': 'RESULTS_GMSH_nn.msh.', 'WRITE_MODAL_OUTPUT': 'All 103 outputs.',
    'WRITE_SOLVER_INFO': 'ARPACK_SOLVER_INFO.dat.', 'EVALUATE_GRID_MODES': 'Mode displacements at the grid nodes.',
    'EVALUATE_CELL_MODES': 'Same for one cell.', 'WRITE_MODAL_VTK': 'RESULTS_DYN_PARA.vtk.', 'WRITE_MODAL_GMSH': 'RESULTS_DYN_GMSH.msh.',
    'WRITE_MATRIX_DUMPS': 'K_MAT, M_MAT, FORCES, UNKNOWN in WORK.', 'WRITE_CSR': 'Dump a CSR matrix as row, column, value lines.',
    'WRITE_VECTOR': 'Dump a vector.', 'ADD_WARNING': 'Append a text to the warning list.',
    'WRITE_WARNING_FILE': 'REPORT/WARNING_file.dat.', 'INTEGER_TEXT': 'Integer to text without blanks.',
    'PLACE_SETUP': 'Load node coordinates and frames of one element/sub-element for point evaluation.',
    'FREE_PLACE': 'Release a PLACE_TYPE.',
    'PLACE_EVALUATE': 'Shapes, local gradients and physical position at a natural point.',
    'STATE_FROM_PLACE': 'Displacement, strain and stress at the point last evaluated (MITC rows included).',
    'DISPLACEMENT_FROM_PLACE': 'Global displacement of several DOF vectors (mode shapes) at the point.',
    'TRANSFORM_INVERSE': 'Inverse of the strain transform of an orthogonal rotation (its transpose pattern).',
    'LOCATE_POINT': 'Find (element, sub-element, natural coordinates) containing a physical point: bounding-box prefilter, then Newton.',
    'POINT_NEAR_ELEMENT': 'Cheap rejection with the bounding box of the structural nodes.',
    'NEWTON_LOCATE': 'Newton iteration on the isoparametric map to find the natural coordinates.',
    'NATURAL_INSIDE': 'True when natural coordinates lie inside the reference element.',
    'INVERT_3X3': 'Invert a 3x3 matrix with its determinant.',
    # ---------------------------------------------------------- SOLVERS
    'DSAUPD': 'ARPACK reverse-communication driver (external).', 'DSEUPD': 'ARPACK eigenvalue/eigenvector extraction (external).',
    'DSYGV': 'LAPACK dense generalised symmetric eigenproblem (external).',
    'SOLVE_MODAL_PROBLEM': 'Eigenpairs closest to a shift: ARPACK shift-invert, or dense LAPACK for small problems; sorted and with residuals.',
    'SOLVE_ARPACK': 'Reverse-communication loop of dsaupd in mode 3 with a PARDISO factorization of K - sigma M.',
    'SOLVE_DENSE': 'Dense fallback with dsygv for N <= 400 or almost all modes requested.',
    'SORT_MODES': 'Ascending sort of eigenvalues, vectors follow.',
    'COMPUTE_RESIDUALS': 'Relative residual ||K x - lambda M x|| of every mode.',
    'PARDISO': 'MKL PARDISO entry point (external, ILP64).',
    'PARDISO_FACTORIZE': 'Copy the upper triangle and factorize (phase 12).',
    'PARDISO_SET_SYSTEM': 'Copy the upper triangle into the handle so that the caller may free its matrix.',
    'PARDISO_FACTOR_LOADED': 'Factorize the matrix stored in the handle; Cholesky breakdown is retried as symmetric indefinite with a warning.',
    'PARDISO_FREE_INTERNAL': 'Free only the PARDISO internal memory (phase -1), keep the matrix.',
    'PARDISO_SOLVE': 'Solve with the stored factors (phase 33).', 'PARDISO_RELEASE': 'Free PARDISO memory and the stored matrix.',
    'EXTRACT_UPPER_TRIANGLE': 'Upper triangle of a symmetric CSR matrix.',
    'PARDISO_HINT': 'Plain-language meaning of a PARDISO error code.',
    'SOLVE_SYMMETRIC_POSITIVE_DEFINITE': 'Static solver: set, optionally release the caller matrix, factorize, solve.',
}

ARG_DOC = {
    'STATUS': 'Status of the call (OK, warning or error with message and source).',
    'MODEL': 'Complete input model (all databases).',
    'CACHE': 'Model cache built by BUILD_MODEL_CACHE.',
    'RESULTS': 'Analysis results container.',
    'NODES': 'Structural node database.',
    'ELEMENTS': 'Structural element database.',
    'KINEMATICS': 'Field-dependent kinematics database.',
    'EXPANSIONS': 'Expansion (section/thickness) mesh database.',
    'RULES': 'Reference quadrature rule database.',
    'LAYOUT': 'Gauss-point layout (global point numbering).',
    'GAUSS_LAYOUT': 'Gauss-point layout (global point numbering).',
    'STRUCTURAL_CACHE': 'Geometry cache of the structural points.',
    'EXPANSION_CACHE': 'Geometry cache of the expansion points.',
    'GEOMETRY': 'Combined Gauss geometry (coordinates, weights).',
    'FRAMES': 'Element reference frames.',
    'MATERIAL_CACHE': 'Resolved constitutive matrices.',
    'MATERIAL_MAP': 'Gauss point -> material cache index.',
    'MATERIALS': 'Material database.', 'LAMINATIONS': 'Lamination database.',
    'DOF_LAYOUT': 'Global DOF numbering.', 'MITC': 'MITC tying data of the element.', 'MITC_DATA': 'MITC tying data of the element.',
    'ELEMENT_INDEX': 'Index of the element in the element database.', 'ELEMENT': 'Element index.',
    'POINT': 'Global Gauss-point index (or physical point).', 'SYSTEM': 'Sparse system (CSR pattern, K, M).',
    'ORDER': 'Order of the matrix, or polynomial/quadrature order (see routine).',
    'ROW_POINTER': 'CSR row pointer (1-based, size N+1).', 'COLUMN_INDEX': 'CSR column indices (1-based).',
    'VALUE': 'Value(s) (see routine).', 'FACTOR': 'PARDISO handle with factors and stored matrix.',
    'FORCE': 'Global force vector.', 'CONSTRAINTS': 'Constrained-DOF set (flags and prescribed values).',
    'TOLERANCE': 'Geometric tolerance.', 'MATRICES': 'Element matrix container (K, M, DOF lists).',
    'FILE_NAME': 'Path of the file.', 'UNIT': 'Fortran unit number.', 'COUNT': 'Number of items.',
    'SOLUTION': 'Global displacement vector.', 'WARNINGS': 'List of warnings for REPORT/WARNING_file.dat.',
    'GRID': 'Output grid.', 'STATE': 'Displacement, strain, stress at output points.',
    'TOPOLOGY': 'Topology code (B2..S1).', 'NATURAL': 'Natural coordinates (xi, eta, nu).',
    'SPEC': 'Expansion specification (family, order, field reference).', 'TERM': 'Expansion term index.',
    'STRUCTURAL_NODE': 'Local structural node index.', 'FIELD': 'Field index (1=U, 2=V, 3=W, ...).',
    'MESH': 'Expansion mesh.', 'MESH_INDEX': 'Index of the expansion mesh.',
    'WITH_MASS': 'Also build the mass matrix.', 'FORCE_GENERAL': 'Force the reference (point-by-point) kernel.',
    'INPUT_PATH': 'Input directory.', 'DATABASE': 'Database being filled.',
    'MESSAGE': 'Message text.', 'TEXT': 'Text.', 'NAME': 'Name.', 'ID': 'Identifier.',
    'A': 'Matrix or operand A.', 'B': 'Matrix or operand B.', 'X': 'Vector or coordinate.', 'Y': 'Result vector.',
    'N': 'Shape function values.', 'DN': 'Shape derivatives.', 'DN_DNATURAL': 'Derivatives with respect to natural coordinates.',
    'PLANE': 'Plane coefficients (A, B, C, D) of A x + B y + C z + D = 0.',
    'DIMENSION': 'Natural dimension.', 'AXIS': 'Active local axes.', 'ACTIVE_AXIS': 'Active local axes of the section.',
    'COORDINATE': 'Coordinates.', 'GRADIENT': 'Gradient (3 components).', 'DERIVATIVE': 'Derivative.',
    'STIFFNESS': 'Stiffness matrix (or values).', 'MASS': 'Mass matrix (or values).',
    'EIGENVALUE': 'Eigenvalues (omega^2).', 'VECTOR': 'Vector(s) / eigenvectors.', 'RESIDUAL': 'Relative residuals.',
    'INFO': 'Solver information (backend, iterations, subspace).', 'NEV': 'Number of requested modes.',
    'SIGMA': 'Spectral shift.', 'MTYPE': 'PARDISO matrix type (2 SPD, -2 symmetric indefinite).',
    'RIGHT_HAND_SIDE': 'Right-hand side vector.', 'PATTERN': 'Reduced CSR pattern with maps.',
    'CONSTRAINED': 'Flags of constrained DOFs.', 'TABLES': 'Lagrange coupling tables (one per expansion mesh).',
    'LIST': 'DOF list of one element.', 'LISTS': 'DOF lists of all elements.', 'TOTAL_DOF': 'Total number of DOFs.',
    'GLOBAL_DOF': 'Global DOF numbers of the local DOFs.', 'PRODUCT': 'Expansion product table.',
    'BASIS_A': 'Expansion functions of the row specification.', 'BASIS_B': 'Expansion functions of the column specification.',
    'WQ': 'Expansion integration weights.', 'NE': 'Number of sub-elements.', 'NQ': 'Expansion points per sub-element.',
    'QO': 'Offset of each sub-element in the expansion point list.', 'APPLICABLE': 'Set to .FALSE. when the separable path cannot be used.',
    'KINEMATIC_INDEX': 'Kinematic index of every structural node.', 'TERM_COUNT': 'Terms per (node, field).',
    'EXPANSION_ORDER': 'Gauss points per direction needed by each expansion mesh.',
    'MODE': 'Mode shape vectors.', 'FREQUENCY': 'Natural frequencies in Hz.',
    'REQUEST': 'Post-processing request (format, frame, cell nodes, split).', 'NUMBER': 'Sequence number of the request.',
    'PLACE': 'Evaluation context: node coordinates, shapes and frames of one element/sub-element.',
    'SUB_ELEMENT': 'Index of the expansion sub-element.', 'TARGET': 'Physical point to locate.',
    'FOUND': 'True when the point lies inside an element.', 'NATURAL_S': 'Structural natural coordinates.',
    'NATURAL_E': 'Expansion natural coordinates.', 'WITH_GRADIENT': 'Also compute local gradients.',
    'LOAD': 'Load components (Fx, Fy, Fz).', 'COMPONENT_ACTIVE': 'Which displacement components are imposed.',
    'COMPONENT_VALUE': 'Imposed values.', 'INCIDENCE': 'Node -> element incidence table.', 'BOUNDARIES': 'Boundary-condition database.',
    'REFERENCE_VECTORS': 'Versor database.', 'ROTATION': 'Rotation matrix (rows = local axes in global coordinates).',
    'IOS': 'I/O status.', 'LINE': 'Text line.',
}

ARG_PROC = {
    ('GLOBAL_DOF', 'NODE_INDEX'): 'Index of the node in the node database.',
    ('GLOBAL_DOF', 'TERM'): 'Term index (1-based) within the (node, field) block.',
    ('EVALUATE_SHAPE', 'N'): 'Output: shape function values.',
    ('BUILD_ISOTROPIC_MATERIAL', 'YOUNG'): 'Young modulus E.',
    ('BUILD_ISOTROPIC_MATERIAL', 'POISSON'): 'Poisson ratio nu.',
    ('BUILD_ISOTROPIC_MATERIAL', 'DENSITY'): 'Mass density rho.',
    ('BUILD_MATERIAL_ROTATION', 'ANGLE_Y_DEG'): 'Rotation about the local y axis (degrees).',
    ('BUILD_MATERIAL_ROTATION', 'ANGLE_Z_DEG'): 'Rotation about the local z axis (degrees).',
    ('BUILD_MATERIAL_ROTATION', 'MATERIAL_FROM_LOCAL'): 'Output: matrix that maps element-frame components to material-frame components.',
    ('SET_ERROR', 'SOURCE'): 'Name of the routine reporting the error.', ('SET_WARNING', 'SOURCE'): 'Name of the routine reporting the warning.',
    ('MERGE_STATUS', 'LOCAL'): 'Status of one step.', ('MERGE_STATUS', 'GLOBAL'): 'Accumulated status of the phase.',
    ('SOLVE_MODAL_PROBLEM', 'ROW_POINTER'): 'CSR row pointer of the reduced (free-DOF) matrices.',
    ('PARDISO_SOLVE', 'SOLUTION'): 'Output: solution vector.',
    ('SORT_PERMUTATION', 'KEY'): 'Array of keys to sort.', ('SORT_PERMUTATION', 'ORDER'): 'Output: permutation.',
    ('BINARY_SEARCH', 'TARGET'): 'Key to find.',
    ('SCATTER_ELEMENT', 'STIFFNESS'): 'Dense element stiffness.', ('SCATTER_ELEMENT', 'MASS'): 'Dense element mass (may be empty).',
    ('ASSEMBLE_MODEL_SYSTEM', 'SYSTEM'): 'Output: K and optionally M in CSR.',
    ('ACCUMULATE_UPPER_PRODUCT', 'A'): 'Left factor, rows = integration rows, columns = DOFs.',
    ('ACCUMULATE_UPPER_PRODUCT', 'B'): 'Right factor (same shape as A).',
    ('ACCUMULATE_UPPER_PRODUCT', 'ROWS'): 'Number of rows actually used.',
    ('ACCUMULATE_UPPER_PRODUCT', 'MATRIX'): 'In/out: receives the upper triangle of A^T B.',
    ('ACCUMULATE_UPPER_PRODUCT', 'INDEX'): 'Optional ascending list of selected columns.',
}


TYPE_DOC = {
    'ANALYSIS_RESULTS_TYPE': 'Results of an analysis: system matrices, constraints, force, solution (101) or modes (103) and solver statistics.',
    'MODEL_CACHE_TYPE': 'Everything derived from the model that does not depend on the analysis: frames, DOF layout, rules, Gauss layout and geometry, material cache.',
    'DOF_LAYOUT_TYPE': 'Field-major global DOF numbering: terms per (node, field), first DOF, range of every field.',
    'SPARSE_SYSTEM_TYPE': 'CSR (1-based, 64-bit) pattern shared by K and M with their value arrays.',
    'DOF_LIST_TYPE': 'Global DOF numbers of the local DOFs of one element, with the Lagrange table and term of every DOF.',
    'COUPLING_TABLE_TYPE': 'COUPLED(t,s): the expansion nodes t and s share a sub-element.',
    'REDUCED_PATTERN_TYPE': 'CSR pattern of the free-DOF sub-matrix and the maps to the full numbering.',
    'STATUS_TYPE': 'Result of any operation: code (0 OK, 1 warning, 2 error), warning counter, last message and its source routine.',
    'TIMER_TYPE': 'CPU and wall-clock timer.',
    'CONSTRAINT_SET_TYPE': 'Constrained-DOF flags and prescribed values.',
    'ELEMENT_MATRIX_TYPE': 'Dense K and M of one element with the description of its local DOFs.',
    'TYING_SET_TYPE': 'Tying points of one MITC set: tensor product of one coordinate list per direction.',
    'MITC_DATA_TYPE': 'MITC data of one element: tied rows, tying sets, shapes and gradients at the tying points.',
    'SPEC_BASIS_TYPE': 'Expansion functions EPS(point, term, 0:3) of one kinematic specification at all expansion points of the element.',
    'EXPANSION_PRODUCT_TYPE': 'Expansion integrals EM(t,s,k,e) for one pair of specifications.',
    'STRUCTURAL_GEOMETRY_CACHE_TYPE': 'Jacobian data and local shape gradients of the structural points.',
    'EXPANSION_GEOMETRY_CACHE_TYPE': 'Jacobian data and local shape gradients of the expansion points.',
    'GAUSS_GEOMETRY_TYPE': 'Combined Gauss points: cache indices, global coordinates and integration weights.',
    'MATERIAL_CACHE_TYPE': 'Distinct resolved constitutive matrices (one per lamination).',
    'GAUSS_MATERIAL_MAP_TYPE': 'Material cache index of every Gauss point.',
    'REFERENCE_RULE_TYPE': 'One reference quadrature rule with shapes and derivatives at its points.',
    'REFERENCE_RULE_DB_TYPE': 'Collection of reference rules.',
    'GAUSS_LAYOUT_TYPE': 'Global numbering of the Gauss points and its decomposition into element, sub-element, structural and expansion point.',
    'MATERIAL_TYPE': 'One material: id, model, density and 6x6 stiffness in the material axes.',
    'MATERIAL_DB_TYPE': 'Material database.',
    'ANALYSIS_TYPE': 'Content of ANALYSIS.dat.',
    'POST_FIELD_REQUEST_TYPE': 'One PARA or GMSH record: format, frame, nodes per cell and the nine subdivision counts.',
    'POST_POINT_REQUEST_TYPE': 'One PNT record.',
    'POST_DB_TYPE': 'Content of POSTPROCESSING.dat.',
    'BOUNDARY_CONDITION_TYPE': 'One D-PLANE or F-POINT record.',
    'BOUNDARY_DB_TYPE': 'Boundary-condition database.',
    'ELEMENT_TYPE': 'One structural element.', 'ELEMENT_DB_TYPE': 'Element database.',
    'EXPANSION_NODE_TYPE': 'Node of an expansion mesh (section or thickness).',
    'EXPANSION_ELEMENT_TYPE': 'Sub-element of an expansion mesh.',
    'EXPANSION_MESH_TYPE': 'One expansion mesh (EXP_MESH_nn / EXP_CONN_nn).', 'EXPANSION_DB_TYPE': 'Expansion mesh database.',
    'NODE_INCIDENCE_TYPE': 'Elements incident to each node (CSR).',
    'EXPANSION_SPEC_TYPE': 'Expansion of one field: family (NONE, TE, LE, HLE, M), order and field reference.',
    'KINEMATIC_TYPE': 'Expansion specification of the nine fields.', 'KINEMATICS_DB_TYPE': 'Kinematics database.',
    'LAMINATION_TYPE': 'One lamination: material and orientation angles.', 'LAMINATION_DB_TYPE': 'Lamination database.',
    'MODEL_TYPE': 'Complete input model.',
    'NODE_TYPE': 'One structural node.', 'NODE_DB_TYPE': 'Node database with sorted-id lookup.',
    'REFERENCE_VECTOR_TYPE': 'One versor.', 'REFERENCE_VECTOR_DB_TYPE': 'Versor database.',
    'ELEMENT_FRAME_DB_TYPE': 'Origin and rotation of the local frame of every element.',
    'POST_GRID_TYPE': 'Output grid: cells with their element, sub-element and the natural coordinates of every grid node.',
    'WARNING_LIST_TYPE': 'Warnings collected for REPORT/WARNING_file.dat.',
    'PLACE_TYPE': 'Geometry and shape data of one (element, sub-element) pair used to evaluate fields at arbitrary points.',
    'POINT_STATE_TYPE': 'Displacement, strain and stress at one point.',
    'QUADRATURE_RULE_TYPE': 'Points and weights of a quadrature rule.',
    'MODAL_INFO_TYPE': 'Statistics of the eigensolver run.',
    'PARDISO_FACTOR_TYPE': 'PARDISO handle: internal pointers, parameters and the stored upper triangle.',
}

COMP_DOC = {
    'SOLUTION_ID': 'Analysis number (101 or 103).', 'SYSTEM': 'Sparse K and M.', 'CONSTRAINTS': 'Constrained DOFs.',
    'FORCE': 'Global force vector.', 'SOLUTION': 'Displacement coefficients in field-major DOF order.',
    'MODE_COUNT': 'Number of modes (requested / converged).', 'EIGENVALUE': 'Eigenvalues omega^2.',
    'FREQUENCY': 'Natural frequencies in Hz.', 'MODE': 'M-orthonormal mode shapes (constrained DOFs = 0).',
    'RESIDUAL': 'Relative residual of every mode.', 'SOLVER_BACKEND': 'ARPACK or DENSE.',
    'SOLVER_ITERATIONS': 'Arnoldi update iterations.', 'SOLVER_OPERATIONS': 'Operator applications.',
    'SOLVER_SUBSPACE': 'Dimension of the Krylov subspace.', 'ASSEMBLY_SECONDS': 'Wall time of the assembly.',
    'SOLVER_SECONDS': 'Wall time of the solver.',
    'FRAMES': 'Element frames.', 'DOF_LAYOUT': 'DOF numbering.', 'RULES': 'Reference rules.', 'GAUSS_LAYOUT': 'Gauss layout.',
    'STRUCTURAL_GEOMETRY': 'Structural geometry cache.', 'EXPANSION_GEOMETRY': 'Expansion geometry cache.',
    'GEOMETRY': 'Combined geometry.', 'MATERIAL_CACHE': 'Material cache.', 'EXPANSION_ORDER': 'Gauss points per direction of each expansion mesh.',
    'MATERIAL_MAP': 'Gauss point to material map.',
    'TERM_COUNT': 'Number of terms of (node, field).', 'FIRST': 'First global DOF of (node, field) or first element of a node.',
    'FIELD_FIRST': 'First DOF of each field.', 'FIELD_LAST': 'Last DOF of each field.', 'TOTAL_DOF': 'Total number of DOFs.',
    'ORDER': 'Order of the matrix / expansion order / quadrature order (see type).',
    'NONZERO_COUNT': 'Number of stored entries.', 'ROW_POINTER': 'CSR row pointer.', 'COLUMN_INDEX': 'CSR column indices.',
    'STIFFNESS': 'Stiffness values or matrix.', 'MASS': 'Mass values or matrix.', 'GLOBAL_DOF': 'Global DOF numbers.',
    'TABLE': 'Lagrange coupling table id (0 = fully coupled).', 'TERM': 'Expansion term of each local DOF.',
    'COUPLED': 'Coupling flags of expansion terms.', 'FREE_TO_GLOBAL': 'Free DOF -> global DOF.',
    'SOURCE_POSITION': 'Position in the full CSR of every reduced entry.',
    'CODE': 'Status code.', 'WARNING_COUNT': 'Number of warnings.', 'MESSAGE': 'Last message.', 'SOURCE': 'Routine that reported it.',
    'NAME': 'Timer name.', 'CPU_BEGIN': 'CPU time at start.', 'CPU_END': 'CPU time at stop.', 'CLOCK_BEGIN': 'Clock count at start.',
    'CLOCK_END': 'Clock count at stop.', 'CLOCK_RATE': 'Clock ticks per second.', 'CLOCK_MAX': 'Clock wrap value.', 'RUNNING': 'Timer running flag.',
    'COUNT': 'Number of items.', 'ACTIVE': 'Flags.', 'VALUE': 'Values.',
    'ELEMENT_INDEX': 'Element index.', 'LOCAL_DOF_COUNT': 'Number of local DOFs.', 'NODE_INDEX': 'Node index of each local node.',
    'KINEMATIC_INDEX': 'Kinematic index of each local node.', 'STRUCTURAL_NODE': 'Local structural node of each local DOF.',
    'FIELD': 'Field of each local DOF (or request list).', 'CSR_POSITION': 'Precomputed CSR positions.',
    'COUNT_1D': 'Tying points per direction.', 'COORDINATE_1D': 'Tying coordinates per direction.',
    'SET_COUNT': 'Number of tying sets.', 'ROW_SET': 'Tying set of each strain row (0 = not tied).', 'SET': 'Tying sets.',
    'SHAPE': 'Shape function values at the tying/rule points.', 'GRADIENT': 'Local-frame gradients.',
    'SPEC': 'Expansion specification.', 'TERMS': 'Number of terms.', 'EPS': 'Expansion functions EPS(point, term, 0:3).',
    'READY': 'Computed flag.', 'EM': 'Expansion integrals EM(t,s,k,e).',
    'ELEMENT_FIRST': 'First point of each element.', 'ELEMENT_LAST': 'Last point of each element.',
    'CENTER_GLOBAL': 'Global coordinate of the structural point.', 'JACOBIAN': 'Jacobian matrices.',
    'INVERSE_JACOBIAN': 'Inverse Jacobians.', 'DETERMINANT': 'Jacobian determinants.', 'DERIVATIVE_OFFSET': 'Offset of the derivative block of each point.',
    'DERIVATIVE_LOCAL': 'Shape gradients in the local frame.', 'ACTIVE_AXIS': 'Active local axes of each mesh.',
    'MESH_ELEMENT_BASE': 'First flat sub-element of each mesh.', 'COORDINATE_LOCAL': 'Local coordinate of the expansion point.',
    'STRUCTURAL_CACHE_INDEX': 'Structural cache index of each point.', 'EXPANSION_CACHE_INDEX': 'Expansion cache index of each point.',
    'COORDINATE_GLOBAL': 'Global coordinates.', 'INTEGRATION_WEIGHT': 'Weight including both Jacobians.',
    'LAMINATION_ID': 'Lamination id.', 'MATERIAL_ID': 'Material id.', 'DENSITY': 'Mass density.',
    'MATERIAL_FROM_LOCAL': 'Rotation material <- element frame.', 'STIFFNESS_LOCAL': 'Stiffness in the element frame.',
    'CACHE_INDEX': 'Material cache index of each point.', 'TOPOLOGY': 'Topology code.', 'NATURAL_DIMENSION': 'Natural dimension.',
    'NODE_COUNT': 'Number of nodes.', 'COORDINATE': 'Coordinates.', 'WEIGHT': 'Weights.', 'DERIVATIVE': 'Shape derivatives.',
    'EXPANSION_ELEMENT_INDEX': 'Sub-element of each point.', 'STRUCTURAL_RULE_INDEX': 'Structural rule of each point.',
    'STRUCTURAL_POINT_INDEX': 'Structural point within its rule.', 'EXPANSION_RULE_INDEX': 'Expansion rule of each point.',
    'EXPANSION_POINT_INDEX': 'Expansion point within its rule.', 'REFERENCE_WEIGHT': 'Product of the two reference weights.',
    'ID': 'Identifier.', 'MODEL': 'Material model code.', 'ITEM': 'List of items.',
    'SOLVER': 'Unused solver code of the legacy input.', 'SHEAR': 'Shear correction of beams, plates, solids.',
    'FORMAT': 'Output format (VTK or GMSH).', 'FRAME': 'Output frame (local or global) or frame id.', 'CELL_NODES': 'Nodes per output cell.',
    'SPLIT': 'Subdivision counts.', 'POINT': 'Point requests or point coordinate.',
    'WRITE_STIFFNESS': 'Dump K.', 'WRITE_MASS': 'Dump M.', 'WRITE_FORCE': 'Dump F.', 'WRITE_UNKNOWN': 'Dump u.', 'WRITE_ENERGY': 'Energy request.',
    'KIND': 'Record kind.', 'PLANE': 'Plane A, B, C, D.', 'NODE_ID': 'Node ids of the element.', 'EXPANSION_ID': 'Expansion mesh used.',
    'FAMILY': 'Expansion family code.', 'FIELD_REFERENCE': 'Index of a user-defined function set.',
    'ANGLE_Y_DEG': 'Angle about y (degrees).', 'ANGLE_Z_DEG': 'Angle about z (degrees).',
    'INPUT_PATH': 'Input directory.', 'ANALYSIS': 'Analysis data.', 'POST': 'Post-processing data.', 'KINEMATICS': 'Kinematics.',
    'NODES': 'Nodes.', 'ELEMENTS': 'Elements.', 'EXPANSIONS': 'Expansion meshes.', 'VECTORS': 'Versors.',
    'MATERIALS': 'Materials.', 'LAMINATIONS': 'Laminations.', 'BOUNDARIES': 'Boundary conditions.',
    'KINEMATIC_ID': 'Kinematic id of the node.', 'ID_LIST': 'Sorted node ids.', 'ID_ORDER': 'Permutation of the sorted ids.',
    'DIRECTION': 'Direction vector.', 'ORIGIN': 'Frame origin (first node).',
    'GLOBAL_TO_LOCAL': 'Rows = local axes in global components (local = R global).', 'LOCAL_TO_GLOBAL': 'Transpose of GLOBAL_TO_LOCAL.',
    'NODES_PER_CELL': 'Nodes per cell.', 'CELL_COUNT': 'Number of cells.', 'CELL_ELEMENT': 'Element of each cell.',
    'CELL_SUB_ELEMENT': 'Sub-element of each cell.', 'CELL_DIMENSION': 'Dimension of each cell.',
    'NATURAL_STRUCTURAL': 'Structural natural coordinates of grid nodes.', 'NATURAL_EXPANSION': 'Expansion natural coordinates of grid nodes.',
    'TEXT': 'Warning texts.', 'MESH': 'Expansion mesh index.', 'SUB_ELEMENT': 'Sub-element index.',
    'STRUCTURAL_DIMENSION': 'Structural dimension.', 'EXPANSION_DIMENSION': 'Expansion dimension.',
    'STRUCTURAL_TOPOLOGY': 'Structural topology.', 'EXPANSION_TOPOLOGY': 'Expansion topology.', 'STRUCTURAL_AXIS': 'Structural axes.',
    'EXPANSION_AXIS': 'Expansion axes.', 'NODE_GLOBAL': 'Global node coordinates.', 'NODE_LOCAL': 'Local node coordinates.',
    'EXPANSION_NODE': 'Expansion node coordinates.', 'SHAPE_STRUCTURAL': 'Structural shapes.', 'NATURAL_DERIVATIVE_S': 'Structural natural derivatives.',
    'GRADIENT_STRUCTURAL': 'Structural local gradients.', 'SHAPE_EXPANSION': 'Expansion shapes.', 'NATURAL_DERIVATIVE_E': 'Expansion natural derivatives.',
    'GRADIENT_EXPANSION': 'Expansion local gradients.', 'EXPANSION_POINT_LOCAL': 'Expansion point in the local frame.',
    'POINT_GLOBAL': 'Physical point.', 'NATURAL_S': 'Structural natural coordinates.', 'MITC': 'MITC tying data.',
    'ELEMENT': 'Element index.', 'ELEMENT_DIMENSION': 'Element dimension.', 'DISPLACEMENT': 'Displacement (global).',
    'STRAIN_LOCAL': 'Strain in the element frame (xx,yy,zz,xz,yz,xy).', 'STRAIN_GLOBAL': 'Strain in the global frame.',
    'STRESS_LOCAL': 'Stress in the element frame.', 'STRESS_GLOBAL': 'Stress in the global frame.',
    'BACKEND': 'Solver used.', 'REQUESTED': 'Requested modes.', 'CONVERGED': 'Converged modes.', 'SUBSPACE': 'Krylov subspace.',
    'ITERATIONS': 'Iterations.', 'OPERATIONS': 'Operator applications.', 'SIGMA': 'Shift.',
    'MTYPE': 'Matrix type.', 'PT': 'PARDISO internal pointers.', 'IPARM': 'PARDISO parameters.',
}


from descriptions2 import MORE_ARG_DOC  # noqa: E402
for _k, _v in MORE_ARG_DOC.items():
    ARG_DOC.setdefault(_k, _v)
