"""Additional argument descriptions (merged into descriptions.ARG_DOC)."""

MORE_ARG_DOC = {
    'ANALYSIS': 'Output: content of ANALYSIS.dat.',
    'BLOCK': 'Output: 3x3 nucleus block.',
    'BLOCK_GLOBAL': 'Output: block in the global frame.',
    'BLOCK_LOCAL': 'Block in the element frame.',
    'B_COLUMN': 'Strain column (6 values) of the DOF; tied rows are replaced on output.',
    'COLUMN': 'Output: strain column (6 values).',
    'COMPONENT': 'Displacement component index (1=u, 2=v, 3=w) or the frame column of the field.',
    'CONNECTIVITY_FILE': 'Path of EXP_CONN_nn.dat.',
    'COORDINATE_LOCAL': 'Section point in the element local frame.',
    'DATA': 'MITC data of the element.',
    'DEBUG_ENABLED': 'True selects debug logging.',
    'DENSITY': 'Mass density rho.',
    'DETERMINANT': 'Output: determinant of the Jacobian.',
    'DISPLACEMENT': 'Output: global displacement components (one column per vector).',
    'DN_DPHYSICAL': 'Output: shape derivatives with respect to the physical coordinates.',
    'ELEMENT_MATRICES': 'Dense element matrices with their DOF lists.',
    'EXPANSION_DIMENSION': 'Natural dimension of the expansion element.',
    'EXPANSION_ELEMENT_INDEX': 'Index of the active expansion sub-element.',
    'EXPANSION_GRADIENT': 'Local gradients of the expansion shape functions (3, node).',
    'EXPANSION_ID': 'Id given to the mesh (index nn of the file).',
    'EXPANSION_SHAPE': 'Shape functions of the expansion sub-element nodes at the point.',
    'EXPANSION_VALUE': 'Expansion factor F.',
    'FACTOR_GRADIENT': 'Gradient of the expansion factor (local frame).',
    'FACTOR_VALUE': 'Expansion factor F_tau.',
    'FULL': 'Output: vector in the full DOF numbering.',
    'FULL_VALUE': 'Values of the full CSR matrix.',
    'GLOBAL_TO_LOCAL': 'Frame rotation (rows = local axes in global components).',
    'INTEGRATION_WEIGHT': 'Weight including the Jacobians.',
    'INVERSE_JACOBIAN': 'Output: inverse Jacobian.',
    'JACOBIAN': 'Output: Jacobian matrix.',
    'KEY': 'Integer keys.',
    'LAMINATION_ID': 'Id of the lamination to resolve.',
    'LOCAL_NODE': 'Local structural node index.',
    'MATERIAL': 'Output: material (id, model, density, stiffness).',
    'MATERIAL_FROM_LOCAL': 'Output: rotation material <- element frame.',
    'MATERIAL_FROM_REFERENCE': 'Rotation material <- reference frame.',
    'MATRIX': 'In/out: matrix receiving A^T B.',
    'MESH_FILE': 'Path of EXP_MESH_nn.dat.',
    'NATURAL_DERIVATIVE': 'Derivatives of the shapes with respect to the natural coordinates.',
    'NODES_PER_CELL': 'Nodes per output cell: 8, 20 or 27.',
    'NODE_LOCAL': 'Local-frame coordinates of the element nodes.',
    'NU_LT': 'Poisson ratio nu_LT.', 'NU_LZ': 'Poisson ratio nu_LZ.', 'NU_TZ': 'Poisson ratio nu_TZ.',
    'OPERATOR': 'Output: 6x3 strain operator.',
    'PATH': 'Input directory.',
    'POINT_MAP': 'Output: Gauss point -> material cache index.',
    'POST': 'Output: content of POSTPROCESSING.dat.',
    'REDUCED': 'Vector on the free DOFs.',
    'REDUCED_VALUE': 'Output: values on the reduced pattern.',
    'REFERENCE_RULES': 'Reference rule database.',
    'RELEASE_SYSTEM': 'True frees the caller matrix right after PARDISO has copied it.',
    'ROWS': 'Number of rows actually used.',
    'RULE': 'Output: quadrature rule.',
    'SET': 'Tying set.',
    'SHAPE': 'Output: shape function values.',
    'SHEAR_LT': 'Shear modulus G_LT.', 'SHEAR_LZ': 'Shear modulus G_LZ.', 'SHEAR_TZ': 'Shear modulus G_TZ.',
    'SORTED_KEY': 'Keys (in the order given by ORDER).',
    'SPLIT': 'Nine subdivision counts of the record.',
    'STIFFNESS_LOCAL': 'Output: stiffness in the element frame.',
    'STIFFNESS_MATERIAL': 'Stiffness in the material axes.',
    'STIFFNESS_REFERENCE': 'Output: stiffness in the reference frame.',
    'STRUCTURAL_GRADIENT': 'Gradient of the structural shape function (local frame).',
    'STRUCTURAL_VALUE': 'Structural shape function N.',
    'TEST_COLUMN': 'Strain column of the test DOF.', 'TEST_COMPONENT': 'Displacement component of the test DOF.',
    'TEST_OPERATOR': 'Strain operator of the test DOF.', 'TEST_VALUE': 'Basis value of the test DOF.',
    'TIMER': 'Timer.',
    'TOKEN': 'Text token such as TE3, LE or NONE.',
    'TRANSFORM': 'Output: 6x6 engineering-strain transformation.',
    'TRIAL_COLUMN': 'Strain column of the trial DOF.', 'TRIAL_COMPONENT': 'Displacement component of the trial DOF.',
    'TRIAL_OPERATOR': 'Strain operator of the trial DOF.', 'TRIAL_VALUE': 'Basis value of the trial DOF.',
    'VECTORS': 'DOF vectors (e.g. mode shapes), one per column.',
    'WEIGHT': 'Output: interpolation weights of the tying points.',
    'YOUNG_L': 'Young modulus along L.', 'YOUNG_T': 'Young modulus along T.', 'YOUNG_Z': 'Young modulus along Z.',
}
