!=======================================================================
!  DENSE REFERENCE ELEMENT MATRICES FOR LINEAR MECHANICS.
!=======================================================================
      MODULE MUL2_ELEMENT_MATRICES

      USE MUL2_KINDS, ONLY: I4, I8, R8
      USE MUL2_STATUS, ONLY: STATUS_TYPE, CLEAR_STATUS,
     &                       SET_ERROR, STATUS_IS_OK
      USE MUL2_NODES, ONLY: NODE_DB_TYPE, FIND_NODE_INDEX
      USE MUL2_ELEMENTS, ONLY: ELEMENT_DB_TYPE
      USE MUL2_TOPOLOGIES, ONLY: TOPOLOGY_NATURAL_DIMENSION
      USE MUL2_KINEMATICS, ONLY: KINEMATICS_DB_TYPE,
     &                           EXPANSION_SPEC_TYPE,
     &                           FIND_KINEMATIC_INDEX,
     &                           FIELD_P, FIELD_T, N_SOLVED_FIELDS
      USE MUL2_EXPANSION_MESHES, ONLY: EXPANSION_DB_TYPE
      USE MUL2_REFERENCE_SYSTEMS, ONLY: ELEMENT_FRAME_DB_TYPE
      USE MUL2_GAUSS_POINTS, ONLY: REFERENCE_RULE_DB_TYPE,
     &                             GAUSS_LAYOUT_TYPE
      USE MUL2_GAUSS_GEOMETRY, ONLY:
     &     STRUCTURAL_GEOMETRY_CACHE_TYPE,
     &     EXPANSION_GEOMETRY_CACHE_TYPE, GAUSS_GEOMETRY_TYPE
      USE MUL2_GAUSS_MATERIALS, ONLY: MATERIAL_CACHE_TYPE,
     &                               GAUSS_MATERIAL_MAP_TYPE,
     &                               STIFFNESS_PART, PART_FULL,
     &                               GENERALIZED_CONSTITUTIVE,
     &                               THERMAL_STRESS_COEFFICIENT
      USE MUL2_DOF_LAYOUT, ONLY: DOF_LAYOUT_TYPE, GLOBAL_DOF
      USE MUL2_POINT_BASES, ONLY: EVALUATE_POINT_FACTORS
      USE MUL2_MITC, ONLY: MITC_DATA_TYPE, MITC_TIE_COLUMN
      USE MUL2_LINEAR_KINEMATICS, ONLY: COMPOSE_PRODUCT_BASIS
      USE MUL2_LINEAR_KINEMATICS, ONLY:
     &     BUILD_DISPLACEMENT_OPERATOR
      USE MUL2_DENSE_PRODUCTS, ONLY: ACCUMULATE_UPPER_PRODUCT,
     &                               ACCUMULATE_PRODUCT
      USE MUL2_SEPARABLE_KERNEL, ONLY: BUILD_SEPARABLE_MATRICES

      IMPLICIT NONE
      PRIVATE

      TYPE, PUBLIC :: ELEMENT_MATRIX_TYPE
        INTEGER(I4) :: ELEMENT_INDEX = 0_I4
        INTEGER(I4) :: LOCAL_DOF_COUNT = 0_I4
        INTEGER(I8), ALLOCATABLE :: GLOBAL_DOF(:)
        INTEGER(I4), ALLOCATABLE :: NODE_INDEX(:)
        INTEGER(I4), ALLOCATABLE :: KINEMATIC_INDEX(:)
        INTEGER(I4), ALLOCATABLE :: STRUCTURAL_NODE(:)
        INTEGER(I4), ALLOCATABLE :: FIELD(:)
        INTEGER(I4), ALLOCATABLE :: TERM(:)
        INTEGER(I8), ALLOCATABLE :: CSR_POSITION(:,:)
        REAL(R8), ALLOCATABLE :: STIFFNESS(:,:)
        REAL(R8), ALLOCATABLE :: MASS(:,:)
!       INTERNAL FORCE OF THE NONLINEAR (TOTAL LAGRANGIAN) ELEMENT.
        REAL(R8), ALLOCATABLE :: INTERNAL_FORCE(:)
      END TYPE ELEMENT_MATRIX_TYPE

      INTEGER(I4), PARAMETER :: MAX_BATCH = 128_I4

!  WORKSPACE OF THE POINT-BY-POINT KERNELS. THE BASIS OF A DEGREE OF
!  FREEDOM IS N_NODE * F_TERM: THE STRUCTURAL FACTORS (ONE PER NODE) AND
!  THE EXPANSION FACTORS (ONE PER TERM AND PER DISTINCT EXPANSION) ARE
!  EVALUATED ONCE PER POINT AND COMBINED FOR EVERY DOF, INSTEAD OF
!  RE-EVALUATING BOTH FOR EACH OF THE (OFTEN HUNDREDS OF) DOFS.
      TYPE :: POINT_WORK_TYPE
        INTEGER(I4) :: N_MEMO = 0_I4
        INTEGER(I4), ALLOCATABLE :: MEMO_OF(:)
        INTEGER(I4), ALLOCATABLE :: MEMO_NODE(:)
        INTEGER(I4), ALLOCATABLE :: MEMO_TERMS(:)
        INTEGER(I4), ALLOCATABLE :: MEMO_KIN(:)
        INTEGER(I4), ALLOCATABLE :: MEMO_FIELD(:)
        REAL(R8), ALLOCATABLE :: SVAL(:)
        REAL(R8), ALLOCATABLE :: SGRAD(:,:)
        REAL(R8), ALLOCATABLE :: FVAL(:,:)
        REAL(R8), ALLOCATABLE :: FGRAD(:,:,:)
        REAL(R8), ALLOCATABLE :: VALUE(:)
        REAL(R8), ALLOCATABLE :: BCOL(:,:)
        REAL(R8), ALLOCATABLE :: GRAD(:,:)
      END TYPE POINT_WORK_TYPE

!  CONTRACT OF A POINT FOR THE STATE-DEPENDENT OPERATORS (GEOMETRIC AND
!  NONLINEAR MATRICES), FILLED BY EVERY KERNEL (ORDINARY OR CURVED):
!    VALUE(I)        BASIS OF THE DOF I
!    BCOL(:,I)       GENERALISED-STRAIN COLUMN IN THE FRAME OF THE POINT
!    GRAD(:,I)       GRADIENT OF THE BASIS IN THE FRAME OF THE POINT
!    DIRECTION(:,I)  DISPLACEMENT DIRECTION OF THE DOF IN THAT FRAME
!                    (ZERO FOR THE POTENTIAL AND THE TEMPERATURE)
!  AND THE WORK ARRAYS OF THE OPERATORS.
      TYPE :: POINT_STATE_WORK_TYPE
        REAL(R8), ALLOCATABLE :: VALUE(:)
        REAL(R8), ALLOCATABLE :: BCOL(:,:)
        REAL(R8), ALLOCATABLE :: GRAD(:,:)
        REAL(R8), ALLOCATABLE :: DIRECTION(:,:)
        REAL(R8), ALLOCATABLE :: B_TOTAL(:,:)
        REAL(R8), ALLOCATABLE :: MB(:,:)
        REAL(R8), ALLOCATABLE :: SG(:,:)
        REAL(R8), ALLOCATABLE :: A_STACK(:,:)
        REAL(R8), ALLOCATABLE :: B_STACK(:,:)
      END TYPE POINT_STATE_WORK_TYPE

      PUBLIC :: BUILD_LINEAR_ELEMENT_MATRICES
      PUBLIC :: BUILD_ELEMENT_DOF_LIST
      PUBLIC :: BUILD_NONLINEAR_ELEMENT_MATRICES
      PUBLIC :: CLEAR_ELEMENT_MATRIX
      PUBLIC :: POINT_STATE_WORK_TYPE
      PUBLIC :: SETUP_POINT_STATE_WORK
      PUBLIC :: GEOMETRIC_POINT
      PUBLIC :: NONLINEAR_POINT
      PUBLIC :: MIRROR_UPPER_TRIANGLE

      CONTAINS

      SUBROUTINE BUILD_LINEAR_ELEMENT_MATRICES(ELEMENT_INDEX,
     &     NODES, ELEMENTS, KINEMATICS, EXPANSIONS, DOF_LAYOUT,
     &     RULES, GAUSS_LAYOUT, STRUCTURAL_CACHE,
     &     EXPANSION_CACHE, GEOMETRY, FRAMES, MATERIAL_CACHE,
     &     MATERIAL_MAP, MATRICES, STATUS, MITC, WITH_MASS,
     &     FORCE_GENERAL, PART, WITH_STIFFNESS, COUPLING, GEOMETRIC,
     &     U0)

      INTEGER(I4), INTENT(IN) :: ELEMENT_INDEX
      TYPE(NODE_DB_TYPE), INTENT(IN) :: NODES
      TYPE(ELEMENT_DB_TYPE), INTENT(IN) :: ELEMENTS
      TYPE(KINEMATICS_DB_TYPE), INTENT(IN) :: KINEMATICS
      TYPE(EXPANSION_DB_TYPE), INTENT(IN) :: EXPANSIONS
      TYPE(DOF_LAYOUT_TYPE), INTENT(IN) :: DOF_LAYOUT
      TYPE(REFERENCE_RULE_DB_TYPE), INTENT(IN) :: RULES
      TYPE(GAUSS_LAYOUT_TYPE), INTENT(IN) :: GAUSS_LAYOUT
      TYPE(STRUCTURAL_GEOMETRY_CACHE_TYPE), INTENT(IN) ::
     &  STRUCTURAL_CACHE
      TYPE(EXPANSION_GEOMETRY_CACHE_TYPE), INTENT(IN) ::
     &  EXPANSION_CACHE
      TYPE(GAUSS_GEOMETRY_TYPE), INTENT(IN) :: GEOMETRY
      TYPE(ELEMENT_FRAME_DB_TYPE), INTENT(IN) :: FRAMES
      TYPE(MATERIAL_CACHE_TYPE), INTENT(IN) :: MATERIAL_CACHE
      TYPE(GAUSS_MATERIAL_MAP_TYPE), INTENT(IN) :: MATERIAL_MAP
      TYPE(ELEMENT_MATRIX_TYPE), INTENT(INOUT) :: MATRICES
      TYPE(STATUS_TYPE), INTENT(OUT) :: STATUS
      TYPE(MITC_DATA_TYPE), INTENT(IN), OPTIONAL :: MITC
      LOGICAL, INTENT(IN), OPTIONAL :: WITH_MASS
      LOGICAL, INTENT(IN), OPTIONAL :: FORCE_GENERAL
!     PART: PART_FULL, PART_NORMAL OR PART_SHEAR OF THE CONSTITUTIVE
!     MATRIX (SELECTIVE INTEGRATION); WITH_STIFFNESS = .FALSE. SKIPS K.
      INTEGER(I4), INTENT(IN), OPTIONAL :: PART
      LOGICAL, INTENT(IN), OPTIONAL :: WITH_STIFFNESS
!     COUPLING = .TRUE.: STIFFNESS RECEIVES ONLY THE THERMOELASTIC
!     COUPLING BLOCK K(U,T) = - SUM_P W B^T (C ALPHA) N_T (NOT
!     SYMMETRIC: THE BLOCK K(T,U) IS ZERO IN THE STATIONARY PROBLEM).
      LOGICAL, INTENT(IN), OPTIONAL :: COUPLING
!     GEOMETRIC = .TRUE.: STIFFNESS RECEIVES THE GEOMETRIC (INITIAL
!     STRESS) MATRIX OF THE STATE U0 (GLOBAL DOF VECTOR):
!     K_G(I,J) = SUM_P W (D_I.D_J) GRAD N_I . S GRAD N_J,
!     WITH S THE STRESS TENSOR OF U0 (ELEMENT FRAME) AND D THE LOCAL
!     DIRECTION OF THE DISPLACEMENT COMPONENT OF A DOF.
      LOGICAL, INTENT(IN), OPTIONAL :: GEOMETRIC
      REAL(R8), INTENT(IN), OPTIONAL :: U0(:)
      LOGICAL :: GEOMETRY_REQUESTED
      REAL(R8), ALLOCATABLE :: GRAD_STORE(:,:)
      REAL(R8), ALLOCATABLE :: UVALUE(:)
      TYPE(POINT_STATE_WORK_TYPE) :: SWORK
      REAL(R8) :: GRAD_POINT(3)
      INTEGER(I4) :: CPART
      INTEGER(I4) :: CDIM
      LOGICAL :: STIFFNESS_REQUESTED
      LOGICAL :: SEPARABLE
      TYPE(MITC_DATA_TYPE) :: MITC_DATA
      TYPE(STATUS_TYPE) :: LOCAL_STATUS
      REAL(R8), ALLOCATABLE :: BASIS_VALUE(:,:)
      REAL(R8), ALLOCATABLE :: B_TEST(:,:)
      REAL(R8), ALLOCATABLE :: B_WEIGHTED(:,:)
      REAL(R8) :: B_COLUMN(12)
      REAL(R8) :: STIFFNESS_LOCAL(12,12)
      REAL(R8) :: WEIGHT
      REAL(R8) :: POINT_VALUE
      REAL(R8) :: BETA(6)
      REAL(R8), ALLOCATABLE :: THETA_VALUE(:)
      TYPE(POINT_WORK_TYPE) :: PWORK
      LOGICAL :: THERMAL_REQUESTED
      INTEGER(I4) :: NR
      REAL(R8) :: POINT_MASS(MAX_BATCH)
      REAL(R8) :: POINT_CAPACITY(MAX_BATCH)
      INTEGER(I8) :: POINT
      INTEGER(I8) :: FIRST_POINT
      INTEGER(I8) :: LAST_POINT
      INTEGER(I4) :: MATERIAL_INDEX
      INTEGER(I4) :: N_DOF
      INTEGER(I4) :: BATCH
      INTEGER(I4) :: COUNT
      INTEGER(I4) :: I
      INTEGER(I4) :: J
      INTEGER(I4) :: Q
      LOGICAL :: MASS_REQUESTED

      CALL CLEAR_STATUS(STATUS)
      CALL CLEAR_ELEMENT_MATRIX(MATRICES)
      IF (PRESENT(MITC)) MITC_DATA = MITC
      MASS_REQUESTED = .TRUE.
      IF (PRESENT(WITH_MASS)) MASS_REQUESTED = WITH_MASS
      CPART = PART_FULL
      IF (PRESENT(PART)) CPART = PART
!     NUMBER OF GENERALISED STRAIN ROWS: 6 (MECHANICS) OR 9 (WITH THE
!     POTENTIAL GRADIENT OF THE ELECTRIC FIELD, FIELD 5).
      NR = 6_I4
      CDIM = TOPOLOGY_NATURAL_DIMENSION(
     &       ELEMENTS%ITEM(ELEMENT_INDEX)%TOPOLOGY)
      STIFFNESS_REQUESTED = .TRUE.
      IF (PRESENT(WITH_STIFFNESS)) STIFFNESS_REQUESTED = WITH_STIFFNESS
      CALL VALIDATE_INPUT(ELEMENT_INDEX, NODES, ELEMENTS,
     &     KINEMATICS, DOF_LAYOUT, GAUSS_LAYOUT, GEOMETRY,
     &     FRAMES, MATERIAL_CACHE, MATERIAL_MAP, STATUS)
      IF (.NOT. STATUS_IS_OK(STATUS)) RETURN

      CALL BUILD_ELEMENT_DOF_LIST(ELEMENT_INDEX, NODES, ELEMENTS,
     &     KINEMATICS, DOF_LAYOUT, MATRICES, STATUS)
      IF (.NOT. STATUS_IS_OK(STATUS)) RETURN

      N_DOF = MATRICES%LOCAL_DOF_COUNT
      ALLOCATE(MATRICES%STIFFNESS(N_DOF,N_DOF))
      MATRICES%STIFFNESS = 0.0_R8
      IF (MASS_REQUESTED) THEN
        ALLOCATE(MATRICES%MASS(N_DOF,N_DOF))
        MATRICES%MASS = 0.0_R8
        ALLOCATE(BASIS_VALUE(MAX_BATCH,N_DOF))
      ELSE
!       THE SPARSE SCATTER ONLY READS MASS WHEN IT IS ALLOCATED.
        ALLOCATE(MATRICES%MASS(0,0))
      END IF
!     SEPARABLE CUF PATH (STRUCTURAL AND EXPANSION POINTS ADD UP
!     INSTEAD OF MULTIPLYING). THE POINT-BY-POINT PATH BELOW IS THE
!     REFERENCE AND THE FALLBACK FOR NON-SEPARABLE ELEMENTS.
      SEPARABLE = .FALSE.
      THERMAL_REQUESTED = .FALSE.
      IF (PRESENT(COUPLING)) THERMAL_REQUESTED = COUPLING
      GEOMETRY_REQUESTED = .FALSE.
      IF (PRESENT(GEOMETRIC)) GEOMETRY_REQUESTED = GEOMETRIC
      IF (GEOMETRY_REQUESTED) THEN
        IF (.NOT. PRESENT(U0)) THEN
          CALL SET_ERROR(STATUS, 'BUILD_LINEAR_ELEMENT_MATRICES',
     &                   'THE GEOMETRIC MATRIX NEEDS A STATE VECTOR')
          RETURN
        END IF
        ALLOCATE(GRAD_STORE(3,N_DOF), UVALUE(N_DOF))
        CALL SETUP_POINT_STATE_WORK(N_DOF, 12_I4, SWORK)
        DO I = 1_I4, N_DOF
          UVALUE(I) = U0(MATRICES%GLOBAL_DOF(I))
          SWORK%DIRECTION(:,I) = 0.0_R8
          IF (MATRICES%FIELD(I) .LE. 3_I4) SWORK%DIRECTION(:,I) =
     &      FRAMES%GLOBAL_TO_LOCAL(:,MATRICES%FIELD(I),ELEMENT_INDEX)
        END DO
      END IF
      IF (THERMAL_REQUESTED .OR. GEOMETRY_REQUESTED) THEN
        ALLOCATE(THETA_VALUE(N_DOF))
      ELSE IF (.NOT. PRESENT(FORCE_GENERAL)) THEN
        CALL TRY_SEPARABLE()
      ELSE IF (.NOT. FORCE_GENERAL) THEN
        CALL TRY_SEPARABLE()
      END IF
      IF (.NOT. STATUS_IS_OK(STATUS)) RETURN
      IF (SEPARABLE) THEN
        CALL MIRROR_UPPER_TRIANGLE(MATRICES, MASS_REQUESTED)
        RETURN
      END IF
      MATRICES%STIFFNESS = 0.0_R8
      IF (MASS_REQUESTED) MATRICES%MASS = 0.0_R8
!     BATCH OF POINTS: K = SUM_P (B_P)T (W_P C B_P) IS ONE MATRIX
!     PRODUCT OVER 6*BATCH ROWS, INSTEAD OF A SCALAR NUCLEUS PER PAIR.
      IF (ANY(MATRICES%FIELD .EQ. FIELD_P)) NR = 9_I4
      IF (ANY(MATRICES%FIELD .EQ. FIELD_T)) NR = 12_I4
      BATCH = MAX(1_I4, MIN(MAX_BATCH, INT(2.0E6_R8/
     &        (REAL(NR,R8)*REAL(N_DOF,R8)),I4)))
      ALLOCATE(B_TEST(NR*BATCH,N_DOF))
      ALLOCATE(B_WEIGHTED(NR*BATCH,N_DOF))
      CALL SETUP_POINT_WORK(MATRICES, KINEMATICS, PWORK)

      FIRST_POINT = GAUSS_LAYOUT%ELEMENT_FIRST(ELEMENT_INDEX)
      DO WHILE (FIRST_POINT .LE.
     &          GAUSS_LAYOUT%ELEMENT_LAST(ELEMENT_INDEX))
        LAST_POINT = MIN(GAUSS_LAYOUT%ELEMENT_LAST(ELEMENT_INDEX),
     &                   FIRST_POINT+INT(BATCH,I8)-1_I8)
        COUNT = INT(LAST_POINT-FIRST_POINT+1_I8,I4)
        DO POINT = FIRST_POINT, LAST_POINT
          Q = INT(POINT-FIRST_POINT,I4)
          MATERIAL_INDEX = MATERIAL_MAP%CACHE_INDEX(POINT)
          IF (MATERIAL_INDEX .LT. 1_I4 .OR. MATERIAL_INDEX .GT.
     &        MATERIAL_CACHE%COUNT) THEN
            CALL SET_ERROR(STATUS,
     &        'BUILD_LINEAR_ELEMENT_MATRICES',
     &        'GAUSS POINT MATERIAL INDEX IS OUT OF RANGE')
            RETURN
          END IF
          WEIGHT = GEOMETRY%INTEGRATION_WEIGHT(POINT)
          STIFFNESS_LOCAL = WEIGHT*GENERALIZED_CONSTITUTIVE(
     &                      MATERIAL_CACHE, MATERIAL_INDEX, CPART, CDIM)
          POINT_MASS(Q+1_I4) = WEIGHT*
     &      MATERIAL_CACHE%DENSITY(MATERIAL_INDEX)
          POINT_CAPACITY(Q+1_I4) = POINT_MASS(Q+1_I4)*
     &      MATERIAL_CACHE%SPECIFIC_HEAT(MATERIAL_INDEX)
          IF (THERMAL_REQUESTED .OR. GEOMETRY_REQUESTED) THEN
            THETA_VALUE = 0.0_R8
            BETA = THERMAL_STRESS_COEFFICIENT(MATERIAL_CACHE,
     &                                        MATERIAL_INDEX)
          END IF
          CALL EVALUATE_POINT_COLUMNS(POINT, ELEMENT_INDEX,
     &         ELEMENTS, KINEMATICS, EXPANSIONS, RULES, GAUSS_LAYOUT,
     &         STRUCTURAL_CACHE, EXPANSION_CACHE, GEOMETRY, FRAMES,
     &         MATRICES, MITC_DATA, PWORK, LOCAL_STATUS)
          DO I = 1_I4, N_DOF
            POINT_VALUE = PWORK%VALUE(I)
            B_COLUMN = PWORK%BCOL(:,I)
            GRAD_POINT = PWORK%GRAD(:,I)
            IF (MASS_REQUESTED) BASIS_VALUE(Q+1_I4,I) = POINT_VALUE
            IF (THERMAL_REQUESTED .OR. GEOMETRY_REQUESTED) THEN
              IF (MATRICES%FIELD(I) .EQ. FIELD_T) THETA_VALUE(I) =
     &          POINT_VALUE
            END IF
            IF (GEOMETRY_REQUESTED) GRAD_STORE(:,I) = GRAD_POINT
            IF (.NOT. STATUS_IS_OK(LOCAL_STATUS)) THEN
              CALL SET_ERROR(STATUS,
     &          'BUILD_LINEAR_ELEMENT_MATRICES',
     &          TRIM(LOCAL_STATUS%MESSAGE))
              RETURN
            END IF
            B_TEST(NR*Q+1:NR*Q+NR,I) = B_COLUMN(1:NR)
            B_WEIGHTED(NR*Q+1:NR*Q+NR,I) =
     &        MATMUL(STIFFNESS_LOCAL(1:NR,1:NR),B_COLUMN(1:NR))
          END DO
          IF (THERMAL_REQUESTED) THEN
            DO I = 1_I4, N_DOF
              IF (MATRICES%FIELD(I) .GT. 3_I4) CYCLE
              DO J = 1_I4, N_DOF
                IF (MATRICES%FIELD(J) .NE. FIELD_T) CYCLE
                MATRICES%STIFFNESS(I,J) = MATRICES%STIFFNESS(I,J) -
     &            WEIGHT*THETA_VALUE(J)*DOT_PRODUCT(
     &            B_TEST(NR*Q+1:NR*Q+6,I),BETA)
              END DO
            END DO
!           PYROELECTRIC COUPLING: D = ... + P T ENTERS THE POTENTIAL
!           ROW, K(PHI,T) = SUM_P W (GRAD N_PHI . P) N_T.
            IF (MATERIAL_CACHE%ANY_PYRO) THEN
              DO I = 1_I4, N_DOF
                IF (MATRICES%FIELD(I) .NE. FIELD_P) CYCLE
                DO J = 1_I4, N_DOF
                  IF (MATRICES%FIELD(J) .NE. FIELD_T) CYCLE
                  MATRICES%STIFFNESS(I,J) = MATRICES%STIFFNESS(I,J) +
     &              WEIGHT*THETA_VALUE(J)*DOT_PRODUCT(
     &              B_TEST(NR*Q+7:NR*Q+9,I),
     &              MATERIAL_CACHE%PYRO_LOCAL(:,MATERIAL_INDEX))
                END DO
              END DO
            END IF
          END IF
          IF (GEOMETRY_REQUESTED) THEN
!           THE CONTRACT OF THE POINT AND THE SHARED OPERATOR.
            DO I = 1_I4, N_DOF
              SWORK%VALUE(I) = THETA_VALUE(I)
              SWORK%BCOL(1:NR,I) = B_TEST(NR*Q+1:NR*Q+NR,I)
              SWORK%GRAD(:,I) = GRAD_STORE(:,I)
            END DO
            CALL GEOMETRIC_POINT(NR, N_DOF, MATRICES%FIELD, UVALUE,
     &           WEIGHT, STIFFNESS_LOCAL, BETA, SWORK,
     &           MATRICES%STIFFNESS)
          END IF
        END DO
        IF (.NOT. (THERMAL_REQUESTED .OR. GEOMETRY_REQUESTED))
     &    CALL ACCUMULATE_UPPER_PRODUCT(B_TEST,
     &         B_WEIGHTED, NR*COUNT, MATRICES%STIFFNESS)
        IF (MASS_REQUESTED) CALL ADD_MASS(MATRICES, BASIS_VALUE,
     &                                    POINT_MASS, POINT_CAPACITY,
     &                                    COUNT)
        FIRST_POINT = LAST_POINT + 1_I8
      END DO
      IF (GEOMETRY_REQUESTED) CALL MIRROR_UPPER_TRIANGLE(MATRICES,
     &                                                   .FALSE.)
      IF (THERMAL_REQUESTED .OR. GEOMETRY_REQUESTED) RETURN
      IF (.NOT. STIFFNESS_REQUESTED) MATRICES%STIFFNESS = 0.0_R8

      CALL MIRROR_UPPER_TRIANGLE(MATRICES, MASS_REQUESTED)

      CONTAINS

      SUBROUTINE TRY_SEPARABLE()

      CALL BUILD_SEPARABLE_MATRICES(ELEMENT_INDEX, ELEMENTS,
     &     KINEMATICS, EXPANSIONS, RULES, GAUSS_LAYOUT,
     &     STRUCTURAL_CACHE, EXPANSION_CACHE, GEOMETRY, FRAMES,
     &     MATERIAL_CACHE, MATERIAL_MAP, MITC_DATA, MATRICES%FIELD,
     &     MATRICES%STRUCTURAL_NODE, MATRICES%TERM,
     &     MATRICES%KINEMATIC_INDEX, MASS_REQUESTED,
     &     MATRICES%STIFFNESS, MATRICES%MASS, SEPARABLE, STATUS,
     &     CPART, STIFFNESS_REQUESTED)

      END SUBROUTINE TRY_SEPARABLE
      END SUBROUTINE BUILD_LINEAR_ELEMENT_MATRICES

!  TOTAL LAGRANGIAN (ST. VENANT-KIRCHHOFF) ELEMENT AT THE STATE U0.
!    H = GRAD U (ELEMENT FRAME), E = B U + (H^T H)/2 (GREEN STRAIN),
!    SIGMA = M GAMMA (PK2 STRESS, ELECTRIC DISPLACEMENT, HEAT FLUX),
!    F_INT = SUM_P W B(U)^T SIGMA,
!    K_T   = SUM_P W [ B(U)^T M B(U) + (D_I.D_J) GRAD N_I . S GRAD N_J ]
!  WITH B(U) THE VARIATION OF GAMMA (B + THE TERM H^T GRAD N). THE
!  THERMAL AND PYROELECTRIC LOADS ENTER SIGMA, THE COUPLING BLOCKS
!  K(U,T) AND K(PHI,T) ARE ADDED. MITC TIES ONLY THE LINEAR PART.
      SUBROUTINE BUILD_NONLINEAR_ELEMENT_MATRICES(ELEMENT_INDEX,
     &     NODES, ELEMENTS, KINEMATICS, EXPANSIONS, DOF_LAYOUT,
     &     RULES, GAUSS_LAYOUT, STRUCTURAL_CACHE,
     &     EXPANSION_CACHE, GEOMETRY, FRAMES, MATERIAL_CACHE,
     &     MATERIAL_MAP, MATRICES, STATUS, MITC, U0)

      INTEGER(I4), INTENT(IN) :: ELEMENT_INDEX
      TYPE(NODE_DB_TYPE), INTENT(IN) :: NODES
      TYPE(ELEMENT_DB_TYPE), INTENT(IN) :: ELEMENTS
      TYPE(KINEMATICS_DB_TYPE), INTENT(IN) :: KINEMATICS
      TYPE(EXPANSION_DB_TYPE), INTENT(IN) :: EXPANSIONS
      TYPE(DOF_LAYOUT_TYPE), INTENT(IN) :: DOF_LAYOUT
      TYPE(REFERENCE_RULE_DB_TYPE), INTENT(IN) :: RULES
      TYPE(GAUSS_LAYOUT_TYPE), INTENT(IN) :: GAUSS_LAYOUT
      TYPE(STRUCTURAL_GEOMETRY_CACHE_TYPE), INTENT(IN) ::
     &  STRUCTURAL_CACHE
      TYPE(EXPANSION_GEOMETRY_CACHE_TYPE), INTENT(IN) ::
     &  EXPANSION_CACHE
      TYPE(GAUSS_GEOMETRY_TYPE), INTENT(IN) :: GEOMETRY
      TYPE(ELEMENT_FRAME_DB_TYPE), INTENT(IN) :: FRAMES
      TYPE(MATERIAL_CACHE_TYPE), INTENT(IN) :: MATERIAL_CACHE
      TYPE(GAUSS_MATERIAL_MAP_TYPE), INTENT(IN) :: MATERIAL_MAP
      TYPE(ELEMENT_MATRIX_TYPE), INTENT(INOUT) :: MATRICES
      TYPE(STATUS_TYPE), INTENT(OUT) :: STATUS
      TYPE(MITC_DATA_TYPE), INTENT(IN) :: MITC
      REAL(R8), INTENT(IN) :: U0(:)
      REAL(R8), ALLOCATABLE :: COUPLE(:,:)
      REAL(R8), ALLOCATABLE :: UVALUE(:)
      TYPE(POINT_WORK_TYPE) :: PWORK
      TYPE(POINT_STATE_WORK_TYPE) :: SWORK
      REAL(R8) :: MCON(12,12)
      REAL(R8) :: BETA(6)
      REAL(R8) :: WEIGHT
      INTEGER(I8) :: POINT
      INTEGER(I4) :: NR
      INTEGER(I4) :: N_DOF
      INTEGER(I4) :: CDIM
      INTEGER(I4) :: MATERIAL_INDEX
      INTEGER(I4) :: I
      TYPE(STATUS_TYPE) :: LOCAL_STATUS

      CALL CLEAR_STATUS(STATUS)
      CALL CLEAR_ELEMENT_MATRIX(MATRICES)
      CDIM = TOPOLOGY_NATURAL_DIMENSION(
     &       ELEMENTS%ITEM(ELEMENT_INDEX)%TOPOLOGY)
      CALL VALIDATE_INPUT(ELEMENT_INDEX, NODES, ELEMENTS,
     &     KINEMATICS, DOF_LAYOUT, GAUSS_LAYOUT, GEOMETRY,
     &     FRAMES, MATERIAL_CACHE, MATERIAL_MAP, STATUS)
      IF (.NOT. STATUS_IS_OK(STATUS)) RETURN
      CALL BUILD_ELEMENT_DOF_LIST(ELEMENT_INDEX, NODES, ELEMENTS,
     &     KINEMATICS, DOF_LAYOUT, MATRICES, STATUS)
      IF (.NOT. STATUS_IS_OK(STATUS)) RETURN
      N_DOF = MATRICES%LOCAL_DOF_COUNT
      NR = 6_I4
      IF (ANY(MATRICES%FIELD .EQ. FIELD_P)) NR = 9_I4
      IF (ANY(MATRICES%FIELD .EQ. FIELD_T)) NR = 12_I4
      ALLOCATE(MATRICES%STIFFNESS(N_DOF,N_DOF),
     &         MATRICES%INTERNAL_FORCE(N_DOF))
      ALLOCATE(MATRICES%MASS(0,0))
      MATRICES%STIFFNESS = 0.0_R8
      MATRICES%INTERNAL_FORCE = 0.0_R8
      ALLOCATE(UVALUE(N_DOF))
      CALL SETUP_POINT_STATE_WORK(N_DOF, NR, SWORK)
      CALL SETUP_POINT_WORK(MATRICES, KINEMATICS, PWORK)
!     THE COUPLING BLOCKS (NOT SYMMETRIC) ARE KEPT APART FROM THE
!     SYMMETRIC TANGENT, WHICH IS ACCUMULATED ON ITS UPPER TRIANGLE.
      IF (NR .GE. 12_I4 .OR. MATERIAL_CACHE%ANY_PYRO) THEN
        ALLOCATE(COUPLE(N_DOF,N_DOF))
        COUPLE = 0.0_R8
      END IF
      DO I = 1_I4, N_DOF
        UVALUE(I) = U0(MATRICES%GLOBAL_DOF(I))
!       ONLY THE DISPLACEMENT FIELDS HAVE A DIRECTION IN THE FRAME.
        SWORK%DIRECTION(:,I) = 0.0_R8
        IF (MATRICES%FIELD(I) .LE. 3_I4) SWORK%DIRECTION(:,I) =
     &    FRAMES%GLOBAL_TO_LOCAL(:,MATRICES%FIELD(I),ELEMENT_INDEX)
      END DO

      DO POINT = GAUSS_LAYOUT%ELEMENT_FIRST(ELEMENT_INDEX),
     &           GAUSS_LAYOUT%ELEMENT_LAST(ELEMENT_INDEX)
        MATERIAL_INDEX = MATERIAL_MAP%CACHE_INDEX(POINT)
        WEIGHT = GEOMETRY%INTEGRATION_WEIGHT(POINT)
        MCON = GENERALIZED_CONSTITUTIVE(MATERIAL_CACHE,
     &                                  MATERIAL_INDEX, PART_FULL, CDIM)
        BETA = THERMAL_STRESS_COEFFICIENT(MATERIAL_CACHE,
     &                                    MATERIAL_INDEX)
        CALL EVALUATE_POINT_COLUMNS(POINT, ELEMENT_INDEX, ELEMENTS,
     &       KINEMATICS, EXPANSIONS, RULES, GAUSS_LAYOUT,
     &       STRUCTURAL_CACHE, EXPANSION_CACHE, GEOMETRY, FRAMES,
     &       MATRICES, MITC, PWORK, LOCAL_STATUS)
        IF (.NOT. STATUS_IS_OK(LOCAL_STATUS)) THEN
          CALL SET_ERROR(STATUS, 'BUILD_NONLINEAR_ELEMENT_MATRICES',
     &                   TRIM(LOCAL_STATUS%MESSAGE))
          RETURN
        END IF
        DO I = 1_I4, N_DOF
          SWORK%VALUE(I) = PWORK%VALUE(I)
          SWORK%BCOL(1:NR,I) = PWORK%BCOL(1:NR,I)
          SWORK%GRAD(:,I) = PWORK%GRAD(:,I)
        END DO
        CALL NONLINEAR_POINT(NR, N_DOF, MATRICES%FIELD, UVALUE,
     &       WEIGHT, MCON, BETA, MATERIAL_CACHE%ANY_PYRO,
     &       MATERIAL_CACHE%PYRO_LOCAL(:,MATERIAL_INDEX), SWORK,
     &       MATRICES%STIFFNESS, MATRICES%INTERNAL_FORCE, COUPLE)
      END DO
!     SYMMETRIC TANGENT FROM ITS UPPER TRIANGLE, THEN THE COUPLING.
      CALL MIRROR_UPPER_TRIANGLE(MATRICES, .FALSE.)
      IF (ALLOCATED(COUPLE)) MATRICES%STIFFNESS =
     &  MATRICES%STIFFNESS + COUPLE

      END SUBROUTINE BUILD_NONLINEAR_ELEMENT_MATRICES

!  WORK ARRAYS OF THE POINT OPERATORS FOR N_DOF DOFS AND NR STRAIN ROWS.
      SUBROUTINE SETUP_POINT_STATE_WORK(N_DOF, NR, WORK)

      INTEGER(I4), INTENT(IN) :: N_DOF
      INTEGER(I4), INTENT(IN) :: NR
      TYPE(POINT_STATE_WORK_TYPE), INTENT(INOUT) :: WORK

      ALLOCATE(WORK%VALUE(N_DOF), WORK%BCOL(12,N_DOF),
     &         WORK%GRAD(3,N_DOF), WORK%DIRECTION(3,N_DOF))
      ALLOCATE(WORK%B_TOTAL(NR,N_DOF), WORK%MB(NR,N_DOF),
     &         WORK%SG(3,N_DOF), WORK%A_STACK(NR+9,N_DOF),
     &         WORK%B_STACK(NR+9,N_DOF))
      WORK%BCOL = 0.0_R8

      END SUBROUTINE SETUP_POINT_STATE_WORK

!  GEOMETRIC (INITIAL-STRESS) MATRIX OF ONE POINT, UPPER TRIANGLE:
!    S = M(1:6,:) GAMMA(U) - BETA T,
!    K_G(I,J) += W (D_I.D_J) GRAD N_I . S GRAD N_J,
!  A RANK-9 PRODUCT P^T Q. MW IS THE WEIGHTED CONSTITUTIVE MATRIX; THE
!  CONTRACT OF THE POINT IS IN WORK (VALUE: THE TEMPERATURE BASIS OF THE
!  T DOFS). THE CALLER MIRRORS THE MATRIX AT THE END.
      SUBROUTINE GEOMETRIC_POINT(NR, N_DOF, FIELD, UVALUE, WEIGHT, MW,
     &                           BETA, WORK, STIFFNESS)

      INTEGER(I4), INTENT(IN) :: NR
      INTEGER(I4), INTENT(IN) :: N_DOF
      INTEGER(I4), INTENT(IN) :: FIELD(:)
      REAL(R8), INTENT(IN) :: UVALUE(:)
      REAL(R8), INTENT(IN) :: WEIGHT
      REAL(R8), INTENT(IN) :: MW(12,12)
      REAL(R8), INTENT(IN) :: BETA(6)
      TYPE(POINT_STATE_WORK_TYPE), INTENT(INOUT) :: WORK
      REAL(R8), INTENT(INOUT) :: STIFFNESS(:,:)
      REAL(R8) :: GAMMA_V(12)
      REAL(R8) :: STRESS6(6)
      REAL(R8) :: STRESS3(3,3)
      REAL(R8) :: THETA_POINT
      INTEGER(I4) :: I
      INTEGER(I4) :: J

      GAMMA_V = 0.0_R8
      THETA_POINT = 0.0_R8
      DO I = 1_I4, N_DOF
        GAMMA_V(1:NR) = GAMMA_V(1:NR) + WORK%BCOL(1:NR,I)*UVALUE(I)
        IF (FIELD(I) .EQ. FIELD_T) THETA_POINT =
     &    THETA_POINT + WORK%VALUE(I)*UVALUE(I)
      END DO
      STRESS6 = MATMUL(MW(1:6,1:NR),GAMMA_V(1:NR))/
     &          WEIGHT - BETA*THETA_POINT
      STRESS3(1,:) = [STRESS6(1),STRESS6(6),STRESS6(4)]
      STRESS3(2,:) = [STRESS6(6),STRESS6(2),STRESS6(5)]
      STRESS3(3,:) = [STRESS6(4),STRESS6(5),STRESS6(3)]
      DO J = 1_I4, N_DOF
        WORK%SG(:,J) = MATMUL(STRESS3,WORK%GRAD(:,J))
        WORK%A_STACK(1:9,J) = 0.0_R8
        WORK%B_STACK(1:9,J) = 0.0_R8
        IF (FIELD(J) .GT. 3_I4) CYCLE
        DO I = 1_I4, 3_I4
          WORK%A_STACK(3*(I-1)+1:3*I,J) = WORK%DIRECTION(I,J)*
     &      WORK%GRAD(:,J)
          WORK%B_STACK(3*(I-1)+1:3*I,J) = WEIGHT*WORK%DIRECTION(I,J)*
     &      WORK%SG(:,J)
        END DO
      END DO
      CALL ACCUMULATE_UPPER_PRODUCT(WORK%A_STACK(1:9,:),
     &     WORK%B_STACK(1:9,:), 9_I4, STIFFNESS)

      END SUBROUTINE GEOMETRIC_POINT

!  TOTAL LAGRANGIAN (ST. VENANT-KIRCHHOFF) POINT AT THE STATE UVALUE:
!    H = SUM_I U_I D_I (X) GRAD N_I,  E = B U + (H^T H)/2,
!    SIGMA = M E - BETA T (+ P T IN THE POTENTIAL ROWS),
!    F_INT += W B(U)^T SIGMA,
!    K_T += W [B(U)^T M B(U) + (D_I.D_J) GRAD N_I . S GRAD N_J]
!  (UPPER TRIANGLE), WITH B(U) = B + H^T D_I (X) GRAD N_I. THE COUPLING
!  BLOCKS K(U,T), K(PHI,T) GO TO COUPLE WHEN IT IS ALLOCATED.
      SUBROUTINE NONLINEAR_POINT(NR, N_DOF, FIELD, UVALUE, WEIGHT,
     &     MCON, BETA, ANY_PYRO, PYRO, WORK, STIFFNESS, INTERNAL,
     &     COUPLE)

      INTEGER(I4), INTENT(IN) :: NR
      INTEGER(I4), INTENT(IN) :: N_DOF
      INTEGER(I4), INTENT(IN) :: FIELD(:)
      REAL(R8), INTENT(IN) :: UVALUE(:)
      REAL(R8), INTENT(IN) :: WEIGHT
      REAL(R8), INTENT(IN) :: MCON(12,12)
      REAL(R8), INTENT(IN) :: BETA(6)
      LOGICAL, INTENT(IN) :: ANY_PYRO
      REAL(R8), INTENT(IN) :: PYRO(3)
      TYPE(POINT_STATE_WORK_TYPE), INTENT(INOUT) :: WORK
      REAL(R8), INTENT(INOUT) :: STIFFNESS(:,:)
      REAL(R8), INTENT(INOUT) :: INTERNAL(:)
      REAL(R8), ALLOCATABLE, INTENT(INOUT) :: COUPLE(:,:)
      REAL(R8) :: GAMMA_V(12)
      REAL(R8) :: SIGMA(12)
      REAL(R8) :: H(3,3)
      REAL(R8) :: HH(3,3)
      REAL(R8) :: S3(3,3)
      REAL(R8) :: W3(3)
      REAL(R8) :: THETA_POINT
      INTEGER(I4) :: I
      INTEGER(I4) :: J

      GAMMA_V = 0.0_R8
      THETA_POINT = 0.0_R8
      H = 0.0_R8
      DO I = 1_I4, N_DOF
        WORK%B_TOTAL(:,I) = WORK%BCOL(1:NR,I)
        GAMMA_V(1:NR) = GAMMA_V(1:NR) + WORK%BCOL(1:NR,I)*UVALUE(I)
        IF (FIELD(I) .EQ. FIELD_T) THETA_POINT =
     &    THETA_POINT + WORK%VALUE(I)*UVALUE(I)
        IF (FIELD(I) .LE. 3_I4) THEN
          DO J = 1_I4, 3_I4
            H(:,J) = H(:,J) + UVALUE(I)*WORK%DIRECTION(:,I)*
     &               WORK%GRAD(J,I)
          END DO
        END IF
      END DO
!     GREEN STRAIN: LINEAR PART (ALREADY IN GAMMA) + (H^T H)/2.
      HH = MATMUL(TRANSPOSE(H),H)
      GAMMA_V(1) = GAMMA_V(1) + 0.5_R8*HH(1,1)
      GAMMA_V(2) = GAMMA_V(2) + 0.5_R8*HH(2,2)
      GAMMA_V(3) = GAMMA_V(3) + 0.5_R8*HH(3,3)
      GAMMA_V(4) = GAMMA_V(4) + HH(1,3)
      GAMMA_V(5) = GAMMA_V(5) + HH(2,3)
      GAMMA_V(6) = GAMMA_V(6) + HH(1,2)
      SIGMA(1:NR) = MATMUL(MCON(1:NR,1:NR),GAMMA_V(1:NR))
      SIGMA(1:6) = SIGMA(1:6) - BETA*THETA_POINT
      IF (NR .GE. 9_I4 .AND. ANY_PYRO)
     &  SIGMA(7:9) = SIGMA(7:9) + THETA_POINT*PYRO
      S3(1,:) = [SIGMA(1),SIGMA(6),SIGMA(4)]
      S3(2,:) = [SIGMA(6),SIGMA(2),SIGMA(5)]
      S3(3,:) = [SIGMA(4),SIGMA(5),SIGMA(3)]
!     VARIATION OF THE STRAIN: ADD H^T D_I (X) GRAD N_I (SYMMETRIC).
      DO I = 1_I4, N_DOF
        IF (FIELD(I) .GT. 3_I4) CYCLE
        W3 = MATMUL(TRANSPOSE(H),WORK%DIRECTION(:,I))
        WORK%B_TOTAL(1,I) = WORK%B_TOTAL(1,I) + W3(1)*WORK%GRAD(1,I)
        WORK%B_TOTAL(2,I) = WORK%B_TOTAL(2,I) + W3(2)*WORK%GRAD(2,I)
        WORK%B_TOTAL(3,I) = WORK%B_TOTAL(3,I) + W3(3)*WORK%GRAD(3,I)
        WORK%B_TOTAL(4,I) = WORK%B_TOTAL(4,I) + W3(1)*WORK%GRAD(3,I) +
     &                      W3(3)*WORK%GRAD(1,I)
        WORK%B_TOTAL(5,I) = WORK%B_TOTAL(5,I) + W3(2)*WORK%GRAD(3,I) +
     &                      W3(3)*WORK%GRAD(2,I)
        WORK%B_TOTAL(6,I) = WORK%B_TOTAL(6,I) + W3(1)*WORK%GRAD(2,I) +
     &                      W3(2)*WORK%GRAD(1,I)
      END DO
      DO I = 1_I4, N_DOF
        INTERNAL(I) = INTERNAL(I) +
     &    WEIGHT*DOT_PRODUCT(WORK%B_TOTAL(:,I),SIGMA(1:NR))
      END DO
!     TANGENT = B^T (W M) B + (D_I.D_J)(GRAD N_I . S GRAD N_J) W: ONE
!     PRODUCT OVER NR+9 STACKED ROWS (UPPER TRIANGLE).
      DO I = 1_I4, N_DOF
        WORK%MB(:,I) = WEIGHT*MATMUL(MCON(1:NR,1:NR),WORK%B_TOTAL(:,I))
        WORK%SG(:,I) = MATMUL(S3,WORK%GRAD(:,I))
        WORK%A_STACK(1:NR,I) = WORK%B_TOTAL(:,I)
        WORK%B_STACK(1:NR,I) = WORK%MB(:,I)
        DO J = 1_I4, 3_I4
          WORK%A_STACK(NR+3*(J-1)+1:NR+3*J,I) = WORK%DIRECTION(J,I)*
     &      WORK%GRAD(:,I)
          WORK%B_STACK(NR+3*(J-1)+1:NR+3*J,I) = WEIGHT*
     &      WORK%DIRECTION(J,I)*WORK%SG(:,I)
        END DO
      END DO
      CALL ACCUMULATE_UPPER_PRODUCT(WORK%A_STACK, WORK%B_STACK,
     &                              NR+9_I4, STIFFNESS)
!     COUPLING OF THE TEMPERATURE: THERMOELASTIC AND PYROELECTRIC.
      IF (ALLOCATED(COUPLE)) THEN
        DO J = 1_I4, N_DOF
          IF (FIELD(J) .NE. FIELD_T) CYCLE
          DO I = 1_I4, N_DOF
            IF (FIELD(I) .LE. 3_I4) THEN
              COUPLE(I,J) = COUPLE(I,J) - WEIGHT*WORK%VALUE(J)*
     &          DOT_PRODUCT(WORK%B_TOTAL(1:6,I),BETA)
            ELSE IF (FIELD(I) .EQ. FIELD_P .AND. ANY_PYRO) THEN
              COUPLE(I,J) = COUPLE(I,J) + WEIGHT*WORK%VALUE(J)*
     &          DOT_PRODUCT(WORK%B_TOTAL(7:9,I),PYRO)
            END IF
          END DO
        END DO
      END IF

      END SUBROUTINE NONLINEAR_POINT

!  M = SUM_P (W RHO)_P N_P N_PT, WITH N NON-ZERO ONLY BETWEEN DOFS OF
!  THE SAME FIELD: ONE PRODUCT PER FIELD. BASIS_VALUE(POINT,DOF).
      SUBROUTINE ADD_MASS(MATRICES, BASIS_VALUE, POINT_MASS,
     &                    POINT_CAPACITY, COUNT)

      TYPE(ELEMENT_MATRIX_TYPE), INTENT(INOUT) :: MATRICES
      REAL(R8), INTENT(IN) :: BASIS_VALUE(:,:)
      REAL(R8), INTENT(IN) :: POINT_MASS(:)
      REAL(R8), INTENT(IN) :: POINT_CAPACITY(:)
      INTEGER(I4), INTENT(IN) :: COUNT
      REAL(R8), ALLOCATABLE :: SCALED(:,:)
      INTEGER(I4), ALLOCATABLE :: IDX(:)
      INTEGER(I4) :: FIELD
      INTEGER(I4) :: Q
      INTEGER(I4) :: I

      ALLOCATE(SCALED(SIZE(BASIS_VALUE,1),SIZE(BASIS_VALUE,2)))
      DO I = 1_I4, SIZE(BASIS_VALUE,2)
        DO Q = 1_I4, COUNT
          SCALED(Q,I) = BASIS_VALUE(Q,I)*POINT_MASS(Q)
        END DO
      END DO
      DO FIELD = 1_I4, 3_I4
        IDX = PACK([(Q,Q=1_I4,MATRICES%LOCAL_DOF_COUNT)],
     &             MATRICES%FIELD .EQ. FIELD)
        IF (SIZE(IDX) .EQ. 0) CYCLE
        CALL ACCUMULATE_UPPER_PRODUCT(BASIS_VALUE, SCALED, COUNT,
     &                                MATRICES%MASS, IDX)
      END DO
!     THERMAL CAPACITY: RHO C N N^T ON THE TEMPERATURE DOFS.
      IDX = PACK([(Q,Q=1_I4,MATRICES%LOCAL_DOF_COUNT)],
     &           MATRICES%FIELD .EQ. FIELD_T)
      IF (SIZE(IDX) .GT. 0) THEN
        DO I = 1_I4, SIZE(BASIS_VALUE,2)
          DO Q = 1_I4, COUNT
            SCALED(Q,I) = BASIS_VALUE(Q,I)*POINT_CAPACITY(Q)
          END DO
        END DO
        CALL ACCUMULATE_UPPER_PRODUCT(BASIS_VALUE, SCALED, COUNT,
     &                                MATRICES%MASS, IDX)
      END IF
      END SUBROUTINE ADD_MASS

      SUBROUTINE MIRROR_UPPER_TRIANGLE(MATRICES, WITH_MASS)

      TYPE(ELEMENT_MATRIX_TYPE), INTENT(INOUT) :: MATRICES
      LOGICAL, INTENT(IN) :: WITH_MASS
      INTEGER(I4) :: I
      INTEGER(I4) :: J

      DO J = 1_I4, MATRICES%LOCAL_DOF_COUNT
        DO I = J+1_I4, MATRICES%LOCAL_DOF_COUNT
          MATRICES%STIFFNESS(I,J) = MATRICES%STIFFNESS(J,I)
        END DO
      END DO
      IF (WITH_MASS) THEN
        DO J = 1_I4, MATRICES%LOCAL_DOF_COUNT
          DO I = J+1_I4, MATRICES%LOCAL_DOF_COUNT
            MATRICES%MASS(I,J) = MATRICES%MASS(J,I)
          END DO
        END DO
      END IF

      END SUBROUTINE MIRROR_UPPER_TRIANGLE

!  DISTINCT EXPANSIONS OF THE DOFS OF AN ELEMENT: TWO DOFS SHARE A
!  TABLE OF EXPANSION FACTORS WHEN THEIR EXPANSION (FAMILY, ORDER,
!  REFERENCE) IS THE SAME, E.G. THE THREE DISPLACEMENT COMPONENTS.
      SUBROUTINE SETUP_POINT_WORK(MATRICES, KINEMATICS, WORK)

      TYPE(ELEMENT_MATRIX_TYPE), INTENT(IN) :: MATRICES
      TYPE(KINEMATICS_DB_TYPE), INTENT(IN) :: KINEMATICS
      TYPE(POINT_WORK_TYPE), INTENT(INOUT) :: WORK
      INTEGER(I4) :: N_DOF
      INTEGER(I4) :: N_NODE
      INTEGER(I4) :: I
      INTEGER(I4) :: M
      INTEGER(I4) :: K
      INTEGER(I4) :: F

      N_DOF = MATRICES%LOCAL_DOF_COUNT
      N_NODE = SIZE(MATRICES%KINEMATIC_INDEX)
      ALLOCATE(WORK%MEMO_OF(N_DOF), WORK%MEMO_NODE(N_DOF),
     &         WORK%MEMO_TERMS(N_DOF), WORK%MEMO_KIN(N_DOF),
     &         WORK%MEMO_FIELD(N_DOF))
      WORK%N_MEMO = 0_I4
      DO I = 1_I4, N_DOF
        K = MATRICES%KINEMATIC_INDEX(MATRICES%STRUCTURAL_NODE(I))
        F = MATRICES%FIELD(I)
        WORK%MEMO_OF(I) = 0_I4
        DO M = 1_I4, WORK%N_MEMO
          IF (SAME_EXPANSION(
     &        KINEMATICS%ITEM(K)%FIELD(F),
     &        KINEMATICS%ITEM(WORK%MEMO_KIN(M))%FIELD(
     &        WORK%MEMO_FIELD(M)))) THEN
            WORK%MEMO_OF(I) = M
            EXIT
          END IF
        END DO
        IF (WORK%MEMO_OF(I) .EQ. 0_I4) THEN
          WORK%N_MEMO = WORK%N_MEMO + 1_I4
          WORK%MEMO_NODE(WORK%N_MEMO) = MATRICES%STRUCTURAL_NODE(I)
          WORK%MEMO_KIN(WORK%N_MEMO) = K
          WORK%MEMO_FIELD(WORK%N_MEMO) = F
          WORK%MEMO_TERMS(WORK%N_MEMO) = 0_I4
          WORK%MEMO_OF(I) = WORK%N_MEMO
        END IF
        WORK%MEMO_TERMS(WORK%MEMO_OF(I)) = MAX(
     &    WORK%MEMO_TERMS(WORK%MEMO_OF(I)), MATRICES%TERM(I))
      END DO
      ALLOCATE(WORK%SVAL(N_NODE), WORK%SGRAD(3,N_NODE))
      ALLOCATE(WORK%FVAL(MAXVAL(WORK%MEMO_TERMS(1:WORK%N_MEMO)),
     &                   WORK%N_MEMO))
      ALLOCATE(WORK%FGRAD(3,MAXVAL(WORK%MEMO_TERMS(1:WORK%N_MEMO)),
     &                    WORK%N_MEMO))
      ALLOCATE(WORK%VALUE(N_DOF), WORK%BCOL(12,N_DOF),
     &         WORK%GRAD(3,N_DOF))

      END SUBROUTINE SETUP_POINT_WORK

      LOGICAL FUNCTION SAME_EXPANSION(A, B)

      TYPE(EXPANSION_SPEC_TYPE), INTENT(IN) :: A
      TYPE(EXPANSION_SPEC_TYPE), INTENT(IN) :: B

      SAME_EXPANSION = A%FAMILY .EQ. B%FAMILY .AND.
     &  A%ORDER .EQ. B%ORDER .AND.
     &  A%FIELD_REFERENCE .EQ. B%FIELD_REFERENCE

      END FUNCTION SAME_EXPANSION

!  BASIS VALUE, GRADIENT AND GENERALISED-STRAIN COLUMN OF EVERY DOF AT
!  ONE GAUSS POINT (WORK%VALUE, WORK%GRAD, WORK%BCOL).
      SUBROUTINE EVALUATE_POINT_COLUMNS(POINT, ELEMENT_INDEX, ELEMENTS,
     &     KINEMATICS, EXPANSIONS, RULES, GAUSS_LAYOUT,
     &     STRUCTURAL_CACHE, EXPANSION_CACHE, GEOMETRY, FRAMES,
     &     MATRICES, MITC_DATA, WORK, STATUS)

      INTEGER(I8), INTENT(IN) :: POINT
      INTEGER(I4), INTENT(IN) :: ELEMENT_INDEX
      TYPE(ELEMENT_DB_TYPE), INTENT(IN) :: ELEMENTS
      TYPE(KINEMATICS_DB_TYPE), INTENT(IN) :: KINEMATICS
      TYPE(EXPANSION_DB_TYPE), INTENT(IN) :: EXPANSIONS
      TYPE(REFERENCE_RULE_DB_TYPE), INTENT(IN) :: RULES
      TYPE(GAUSS_LAYOUT_TYPE), INTENT(IN) :: GAUSS_LAYOUT
      TYPE(STRUCTURAL_GEOMETRY_CACHE_TYPE), INTENT(IN) ::
     &  STRUCTURAL_CACHE
      TYPE(EXPANSION_GEOMETRY_CACHE_TYPE), INTENT(IN) ::
     &  EXPANSION_CACHE
      TYPE(GAUSS_GEOMETRY_TYPE), INTENT(IN) :: GEOMETRY
      TYPE(ELEMENT_FRAME_DB_TYPE), INTENT(IN) :: FRAMES
      TYPE(ELEMENT_MATRIX_TYPE), INTENT(IN) :: MATRICES
      TYPE(MITC_DATA_TYPE), INTENT(IN) :: MITC_DATA
      TYPE(POINT_WORK_TYPE), INTENT(INOUT) :: WORK
      TYPE(STATUS_TYPE), INTENT(OUT) :: STATUS
      TYPE(EXPANSION_SPEC_TYPE) :: SPEC
      REAL(R8) :: STRUCTURAL_VALUE
      REAL(R8) :: STRUCTURAL_GRADIENT(3)
      REAL(R8) :: FACTOR_VALUE
      REAL(R8) :: FACTOR_GRADIENT(3)
      REAL(R8) :: GRADIENT(3)
      INTEGER(I4) :: N
      INTEGER(I4) :: M
      INTEGER(I4) :: T
      INTEGER(I4) :: I
      INTEGER(I4) :: NODE
      INTEGER(I4) :: MEMO

      CALL CLEAR_STATUS(STATUS)
!     STRUCTURAL FACTORS OF ALL THE NODES (THE EXPANSION OF THE FIRST
!     DISTINCT EXPANSION IS USED ONLY TO REACH THE STRUCTURAL CACHE).
      SPEC = KINEMATICS%ITEM(WORK%MEMO_KIN(1))%FIELD(WORK%MEMO_FIELD(1))
      DO N = 1_I4, SIZE(WORK%SVAL)
        CALL EVALUATE_POINT_FACTORS(POINT, N, 1_I4, SPEC, ELEMENTS,
     &       EXPANSIONS, RULES, GAUSS_LAYOUT, STRUCTURAL_CACHE,
     &       EXPANSION_CACHE, GEOMETRY, WORK%SVAL(N), WORK%SGRAD(:,N),
     &       FACTOR_VALUE, FACTOR_GRADIENT, STATUS)
        IF (.NOT. STATUS_IS_OK(STATUS)) RETURN
      END DO
!     EXPANSION FACTORS OF EVERY TERM OF EVERY DISTINCT EXPANSION.
      DO M = 1_I4, WORK%N_MEMO
        SPEC = KINEMATICS%ITEM(WORK%MEMO_KIN(M))%FIELD(
     &         WORK%MEMO_FIELD(M))
        DO T = 1_I4, WORK%MEMO_TERMS(M)
          CALL EVALUATE_POINT_FACTORS(POINT, WORK%MEMO_NODE(M), T, SPEC,
     &         ELEMENTS, EXPANSIONS, RULES, GAUSS_LAYOUT,
     &         STRUCTURAL_CACHE, EXPANSION_CACHE, GEOMETRY,
     &         STRUCTURAL_VALUE, STRUCTURAL_GRADIENT,
     &         WORK%FVAL(T,M), WORK%FGRAD(:,T,M), STATUS)
          IF (.NOT. STATUS_IS_OK(STATUS)) RETURN
        END DO
      END DO
!     BASIS OF EVERY DOF AND ITS GENERALISED-STRAIN COLUMN.
      DO I = 1_I4, MATRICES%LOCAL_DOF_COUNT
        NODE = MATRICES%STRUCTURAL_NODE(I)
        MEMO = WORK%MEMO_OF(I)
        T = MATRICES%TERM(I)
        CALL COMPOSE_PRODUCT_BASIS(WORK%SVAL(NODE), WORK%SGRAD(:,NODE),
     &       WORK%FVAL(T,MEMO), WORK%FGRAD(:,T,MEMO),
     &       WORK%VALUE(I), GRADIENT)
        WORK%GRAD(:,I) = GRADIENT
        CALL COLUMN_FROM_BASIS(POINT, ELEMENT_INDEX,
     &       MATRICES%FIELD(I), NODE, RULES, GAUSS_LAYOUT, FRAMES,
     &       MITC_DATA, GRADIENT, WORK%FVAL(T,MEMO),
     &       WORK%FGRAD(:,T,MEMO), WORK%VALUE(I), WORK%BCOL(:,I),
     &       STATUS)
        IF (.NOT. STATUS_IS_OK(STATUS)) RETURN
      END DO

      END SUBROUTINE EVALUATE_POINT_COLUMNS

!  GENERALISED-STRAIN COLUMN OF A DOF FROM ITS BASIS GRADIENT: THE
!  DISPLACEMENT OPERATOR (WITH THE MITC TYING WHEN ACTIVE), THE
!  POTENTIAL GRADIENT (ROWS 7-9) OR THE TEMPERATURE GRADIENT (10-12).
      SUBROUTINE COLUMN_FROM_BASIS(POINT, ELEMENT_INDEX, FIELD,
     &     STRUCTURAL_NODE, RULES, GAUSS_LAYOUT, FRAMES, MITC_DATA,
     &     GRADIENT, FACTOR_VALUE, FACTOR_GRADIENT, VALUE, B_COLUMN,
     &     STATUS)

      INTEGER(I8), INTENT(IN) :: POINT
      INTEGER(I4), INTENT(IN) :: ELEMENT_INDEX
      INTEGER(I4), INTENT(IN) :: FIELD
      INTEGER(I4), INTENT(IN) :: STRUCTURAL_NODE
      TYPE(REFERENCE_RULE_DB_TYPE), INTENT(IN) :: RULES
      TYPE(GAUSS_LAYOUT_TYPE), INTENT(IN) :: GAUSS_LAYOUT
      TYPE(ELEMENT_FRAME_DB_TYPE), INTENT(IN) :: FRAMES
      TYPE(MITC_DATA_TYPE), INTENT(IN) :: MITC_DATA
      REAL(R8), INTENT(IN) :: GRADIENT(3)
      REAL(R8), INTENT(IN) :: FACTOR_VALUE
      REAL(R8), INTENT(IN) :: FACTOR_GRADIENT(3)
      REAL(R8), INTENT(INOUT) :: VALUE
      REAL(R8), INTENT(OUT) :: B_COLUMN(12)
      TYPE(STATUS_TYPE), INTENT(OUT) :: STATUS
      REAL(R8) :: B_OPERATOR(6,3)
      REAL(R8) :: NATURAL(3)
      INTEGER(I4) :: RULE_INDEX

      CALL CLEAR_STATUS(STATUS)
      B_COLUMN = 0.0_R8
      IF (FIELD .EQ. FIELD_P) THEN
        B_COLUMN(7:9) = GRADIENT
        VALUE = 0.0_R8
        RETURN
      END IF
      IF (FIELD .EQ. FIELD_T) THEN
        B_COLUMN(10:12) = GRADIENT
        RETURN
      END IF
      CALL BUILD_DISPLACEMENT_OPERATOR(GRADIENT, B_OPERATOR, STATUS)
      IF (.NOT. STATUS_IS_OK(STATUS)) RETURN
      B_COLUMN(1:6) = MATMUL(B_OPERATOR,
     &  FRAMES%GLOBAL_TO_LOCAL(:,FIELD,ELEMENT_INDEX))
      IF (MITC_DATA%ACTIVE) THEN
        RULE_INDEX = GAUSS_LAYOUT%STRUCTURAL_RULE_INDEX(POINT)
        NATURAL = RULES%ITEM(RULE_INDEX)%COORDINATE(
     &            GAUSS_LAYOUT%STRUCTURAL_POINT_INDEX(POINT),1:3)
        CALL MITC_TIE_COLUMN(MITC_DATA, NATURAL, STRUCTURAL_NODE,
     &       FACTOR_VALUE, FACTOR_GRADIENT,
     &       FRAMES%GLOBAL_TO_LOCAL(:,FIELD,ELEMENT_INDEX),
     &       B_COLUMN(1:6), STATUS)
      END IF

      END SUBROUTINE COLUMN_FROM_BASIS

      SUBROUTINE BUILD_ELEMENT_DOF_LIST(ELEMENT_INDEX, NODES,
     &     ELEMENTS, KINEMATICS, DOF_LAYOUT, MATRICES, STATUS)

      INTEGER(I4), INTENT(IN) :: ELEMENT_INDEX
      TYPE(NODE_DB_TYPE), INTENT(IN) :: NODES
      TYPE(ELEMENT_DB_TYPE), INTENT(IN) :: ELEMENTS
      TYPE(KINEMATICS_DB_TYPE), INTENT(IN) :: KINEMATICS
      TYPE(DOF_LAYOUT_TYPE), INTENT(IN) :: DOF_LAYOUT
      TYPE(ELEMENT_MATRIX_TYPE), INTENT(INOUT) :: MATRICES
      TYPE(STATUS_TYPE), INTENT(INOUT) :: STATUS
      INTEGER(I4) :: NODE_INDEX
      INTEGER(I4) :: KINEMATIC_INDEX
      INTEGER(I4) :: LOCAL_NODE
      INTEGER(I4) :: FIELD
      INTEGER(I4) :: TERM
      INTEGER(I4) :: COUNT

      COUNT = 0_I4
      DO LOCAL_NODE = 1_I4,
     & SIZE(ELEMENTS%ITEM(ELEMENT_INDEX)%NODE_ID)
        NODE_INDEX = FIND_NODE_INDEX(NODES,
     &   ELEMENTS%ITEM(ELEMENT_INDEX)%NODE_ID(LOCAL_NODE))
        IF (NODE_INDEX .EQ. 0_I4) THEN
          CALL SET_ERROR(STATUS, 'BUILD_ELEMENT_DOF_LIST',
     &                   'ELEMENT REFERENCES UNKNOWN NODE')
          RETURN
        END IF
        DO FIELD = 1_I4, N_SOLVED_FIELDS
          COUNT = COUNT+DOF_LAYOUT%TERM_COUNT(NODE_INDEX,FIELD)
        END DO
      END DO
      IF (COUNT .LT. 1_I4) THEN
        CALL SET_ERROR(STATUS, 'BUILD_ELEMENT_DOF_LIST',
     &                 'ELEMENT HAS NO MECHANICAL DEGREES OF FREEDOM')
        RETURN
      END IF

      MATRICES%ELEMENT_INDEX = ELEMENT_INDEX
      MATRICES%LOCAL_DOF_COUNT = COUNT
      ALLOCATE(MATRICES%GLOBAL_DOF(COUNT))
      ALLOCATE(MATRICES%NODE_INDEX(SIZE(ELEMENTS%ITEM(ELEMENT_INDEX)%
     &                                  NODE_ID)))
      ALLOCATE(MATRICES%KINEMATIC_INDEX(SIZE(ELEMENTS%ITEM(
     &                                  ELEMENT_INDEX)%NODE_ID)))
      ALLOCATE(MATRICES%STRUCTURAL_NODE(COUNT))
      ALLOCATE(MATRICES%FIELD(COUNT))
      ALLOCATE(MATRICES%TERM(COUNT))
      COUNT = 0_I4
      DO LOCAL_NODE = 1_I4,
     & SIZE(ELEMENTS%ITEM(ELEMENT_INDEX)%NODE_ID)
        NODE_INDEX = FIND_NODE_INDEX(NODES,
     &   ELEMENTS%ITEM(ELEMENT_INDEX)%NODE_ID(LOCAL_NODE))
        KINEMATIC_INDEX = FIND_KINEMATIC_INDEX(KINEMATICS,
     &   NODES%ITEM(NODE_INDEX)%KINEMATIC_ID)
        MATRICES%NODE_INDEX(LOCAL_NODE) = NODE_INDEX
        MATRICES%KINEMATIC_INDEX(LOCAL_NODE) = KINEMATIC_INDEX
        IF (KINEMATIC_INDEX .EQ. 0_I4) THEN
          CALL SET_ERROR(STATUS, 'BUILD_ELEMENT_DOF_LIST',
     &                   'NODE REFERENCES UNKNOWN KINEMATIC')
          RETURN
        END IF
        DO FIELD = 1_I4, N_SOLVED_FIELDS
          DO TERM = 1_I4, DOF_LAYOUT%TERM_COUNT(NODE_INDEX,FIELD)
            COUNT = COUNT+1_I4
            MATRICES%GLOBAL_DOF(COUNT) = GLOBAL_DOF(DOF_LAYOUT,
     &                                      NODE_INDEX,FIELD,TERM)
            MATRICES%STRUCTURAL_NODE(COUNT) = LOCAL_NODE
            MATRICES%FIELD(COUNT) = FIELD
            MATRICES%TERM(COUNT) = TERM
          END DO
        END DO
      END DO

      END SUBROUTINE BUILD_ELEMENT_DOF_LIST

      SUBROUTINE VALIDATE_INPUT(ELEMENT_INDEX, NODES, ELEMENTS,
     &     KINEMATICS, DOF_LAYOUT, GAUSS_LAYOUT, GEOMETRY,
     &     FRAMES, MATERIAL_CACHE, MATERIAL_MAP, STATUS)

      INTEGER(I4), INTENT(IN) :: ELEMENT_INDEX
      TYPE(NODE_DB_TYPE), INTENT(IN) :: NODES
      TYPE(ELEMENT_DB_TYPE), INTENT(IN) :: ELEMENTS
      TYPE(KINEMATICS_DB_TYPE), INTENT(IN) :: KINEMATICS
      TYPE(DOF_LAYOUT_TYPE), INTENT(IN) :: DOF_LAYOUT
      TYPE(GAUSS_LAYOUT_TYPE), INTENT(IN) :: GAUSS_LAYOUT
      TYPE(GAUSS_GEOMETRY_TYPE), INTENT(IN) :: GEOMETRY
      TYPE(ELEMENT_FRAME_DB_TYPE), INTENT(IN) :: FRAMES
      TYPE(MATERIAL_CACHE_TYPE), INTENT(IN) :: MATERIAL_CACHE
      TYPE(GAUSS_MATERIAL_MAP_TYPE), INTENT(IN) :: MATERIAL_MAP
      TYPE(STATUS_TYPE), INTENT(INOUT) :: STATUS

      IF (.NOT. ALLOCATED(NODES%ITEM) .OR.
     &    .NOT. ALLOCATED(ELEMENTS%ITEM) .OR.
     &    .NOT. ALLOCATED(KINEMATICS%ITEM) .OR.
     &    .NOT. ALLOCATED(DOF_LAYOUT%TERM_COUNT)) THEN
        CALL SET_ERROR(STATUS, 'BUILD_LINEAR_ELEMENT_MATRICES',
     &                 'MODEL DATABASES ARE NOT ALLOCATED')
        RETURN
      END IF
      IF (ELEMENT_INDEX .LT. 1_I4 .OR. ELEMENT_INDEX .GT.
     &    SIZE(ELEMENTS%ITEM)) THEN
        CALL SET_ERROR(STATUS, 'BUILD_LINEAR_ELEMENT_MATRICES',
     &                 'ELEMENT INDEX IS OUT OF RANGE')
        RETURN
      END IF
      IF (.NOT. ALLOCATED(GAUSS_LAYOUT%ELEMENT_FIRST) .OR.
     &    .NOT. ALLOCATED(GEOMETRY%INTEGRATION_WEIGHT) .OR.
     &    .NOT. ALLOCATED(FRAMES%GLOBAL_TO_LOCAL) .OR.
     &    .NOT. ALLOCATED(MATERIAL_CACHE%STIFFNESS_LOCAL) .OR.
     &    .NOT. ALLOCATED(MATERIAL_MAP%CACHE_INDEX)) THEN
        CALL SET_ERROR(STATUS, 'BUILD_LINEAR_ELEMENT_MATRICES',
     &                 'INTEGRATION DATABASES ARE NOT ALLOCATED')
        RETURN
      END IF
      IF (GAUSS_LAYOUT%ELEMENT_FIRST(ELEMENT_INDEX) .LT. 1_I8 .OR.
     &    GAUSS_LAYOUT%ELEMENT_LAST(ELEMENT_INDEX) .GT.
     &    GAUSS_LAYOUT%COUNT .OR. GEOMETRY%COUNT .NE.
     &    GAUSS_LAYOUT%COUNT .OR. MATERIAL_MAP%COUNT .NE.
     &    GAUSS_LAYOUT%COUNT) THEN
        CALL SET_ERROR(STATUS, 'BUILD_LINEAR_ELEMENT_MATRICES',
     &                 'GAUSS DATABASES ARE INCONSISTENT')
      END IF

      END SUBROUTINE VALIDATE_INPUT

      SUBROUTINE CLEAR_ELEMENT_MATRIX(MATRICES)

      TYPE(ELEMENT_MATRIX_TYPE), INTENT(INOUT) :: MATRICES

      IF (ALLOCATED(MATRICES%GLOBAL_DOF))
     &  DEALLOCATE(MATRICES%GLOBAL_DOF)
      IF (ALLOCATED(MATRICES%NODE_INDEX))
     &  DEALLOCATE(MATRICES%NODE_INDEX)
      IF (ALLOCATED(MATRICES%KINEMATIC_INDEX))
     &  DEALLOCATE(MATRICES%KINEMATIC_INDEX)
      IF (ALLOCATED(MATRICES%STRUCTURAL_NODE))
     &  DEALLOCATE(MATRICES%STRUCTURAL_NODE)
      IF (ALLOCATED(MATRICES%FIELD)) DEALLOCATE(MATRICES%FIELD)
      IF (ALLOCATED(MATRICES%TERM)) DEALLOCATE(MATRICES%TERM)
      IF (ALLOCATED(MATRICES%CSR_POSITION))
     &  DEALLOCATE(MATRICES%CSR_POSITION)
      IF (ALLOCATED(MATRICES%STIFFNESS))
     &  DEALLOCATE(MATRICES%STIFFNESS)
      IF (ALLOCATED(MATRICES%MASS)) DEALLOCATE(MATRICES%MASS)
      IF (ALLOCATED(MATRICES%INTERNAL_FORCE))
     &  DEALLOCATE(MATRICES%INTERNAL_FORCE)
      MATRICES%ELEMENT_INDEX = 0_I4
      MATRICES%LOCAL_DOF_COUNT = 0_I4

      END SUBROUTINE CLEAR_ELEMENT_MATRIX

      END MODULE MUL2_ELEMENT_MATRICES
