IF(NOT DEFINED SOURCE_ROOT)
  MESSAGE(FATAL_ERROR "SOURCE_ROOT IS REQUIRED")
ENDIF()

FILE(GLOB_RECURSE FORTRAN_FILES
     "${SOURCE_ROOT}/SRC/*.for"
     "${SOURCE_ROOT}/TESTS/*.for")

SET(ERROR_COUNT 0)
FOREACH(FILE_PATH IN LISTS FORTRAN_FILES)
  FILE(STRINGS "${FILE_PATH}" SOURCE_LINES)
  SET(LINE_NUMBER 0)
  FOREACH(SOURCE_LINE IN LISTS SOURCE_LINES)
    MATH(EXPR LINE_NUMBER "${LINE_NUMBER}+1")
    STRING(FIND "${SOURCE_LINE}" "\t" TAB_POSITION)
    IF(NOT TAB_POSITION EQUAL -1)
      MESSAGE(SEND_ERROR
              "TAB IN FIXED-FORM FILE: ${FILE_PATH}:${LINE_NUMBER}")
      MATH(EXPR ERROR_COUNT "${ERROR_COUNT}+1")
    ENDIF()
    STRING(LENGTH "${SOURCE_LINE}" LINE_LENGTH)
    # TEXT AFTER COLUMN 72 IS ALLOWED ONLY AS A MARGIN NOTE: BLANKS, THEN
    # A ! COMMENT (SEE TOOLS/ANNOTATE.PY).
    IF(LINE_LENGTH GREATER 72)
      STRING(SUBSTRING "${SOURCE_LINE}" 72 -1 LINE_TAIL)
      IF(NOT LINE_TAIL MATCHES "^ *!")
        MESSAGE(SEND_ERROR
                "FIXED-FORM LINE > 72: ${FILE_PATH}:${LINE_NUMBER}")
        MATH(EXPR ERROR_COUNT "${ERROR_COUNT}+1")
      ENDIF()
    ENDIF()
  ENDFOREACH()
ENDFOREACH()

IF(ERROR_COUNT GREATER 0)
  MESSAGE(FATAL_ERROR "FIXED-FORM CHECK FAILED: ${ERROR_COUNT} LINES")
ENDIF()

MESSAGE(STATUS "FIXED-FORM CHECK PASSED")
